import '../../abilities/index';
import { abilitiesForMode } from '../../abilities/abilityRegistry';
import type { AbilityGroup, AbilityMode, AbilityParamSpec, AbilitySpec } from '../../abilities/ability';
import { allNodeTypes } from '../../procgen/nodeRegistry';
import type { ReadOnlyTileset } from '../../frontend/readOnlyLibraries';
import {
  DEFAULT_CHARACTER_SIGHT_RADIUS_TILES,
  MAX_CHARACTER_SIGHT_RADIUS_TILES,
  MIN_CHARACTER_SIGHT_RADIUS_TILES,
  characterViewSize,
} from '../../world/vision/characterSight';
import { GOD_VIEW_SIZE } from '../../agents/observation';
import { FAILURES } from '../../agents/failures';
import { allRoutes } from '../agent/routeRegistry';
import { metaTools } from '../agent/agentTools';

const TEMPLATE = `# Procgen world — agent API

You are an agent in an infinite, procedurally generated world. Everything you
can know about the world arrives as an ASCII grid plus a legend; everything you
can do goes through one action per request.

**Every ability in this application is one of the actions below.** The human
sitting at the browser has no powers you lack: their buttons, knobs and drags
call exactly the same actions with the same validation, and each action's row
names the control they would use. A human in an agent view mode reads exactly
the text you receive — nothing more.

## Coordinate system (read this first)

- x grows EAST, y grows SOUTH. The grid is always drawn north-up; it never
  rotates.
- Every observation tells you its own top-left origin: row r, col c of the grid
  is world tile (origin_x + c, origin_y + r).
- You are the '@' at the center of the grid.

## Modes

An agent is created in one of two modes and stays in it for life.

- **god** — a {{GOD_SIZE}}x{{GOD_SIZE}} window centered on you. You see every
  generated tile in the window, and your facing is stated in the observation.
  You move by absolute compass steps, and you can REBUILD THE WORLD: the
  pipeline, library and world actions below are the whole world editor.
- **character** — a {{CHARACTER_SIZE}}x{{CHARACTER_SIZE}} window centered on
  you, but you only see the half-disc in front of you: tiles behind you are
  blank, and so is everything past your {{SIGHT_RADIUS}}-tile sight radius,
  which is why the corners of the grid are blank too. The blank half is how you
  know which way you face — the observation never states it. That half-disc is
  exactly the ground the 2.5D character view renders before its fog closes in,
  which is first person and shows no more of the world than you are told. You move
  relative to your facing and turn in 45-degree steps. Characters can move and
  can change how far they see.

## Sight range, and what it costs

{{SIGHT_RADIUS}} tiles is only the default. A character's sight radius is a
parameter you control, anywhere from {{MIN_SIGHT_RADIUS}} to
{{MAX_SIGHT_RADIUS}} tiles, and there are three ways to set it:

- at birth — \`POST /api/v1/agents\` with \`"sight_radius_tiles": 24\`
- for the rest of the session — the \`set_sight_radius\` action below, which the
  autopilot gets as a tool like any other
- on one read — \`GET /api/v1/agents/{id}/observe?sight_radius_tiles=24\`, which
  also becomes the agent's radius from then on

Values outside the range are clamped rather than rejected. Every observation
reports the radius in force as \`sight_radius_tiles\`, and the grid resizes with
it: the window is always \`radius * 2 + 1\` on a side, so it runs from
{{MIN_SIGHT_RADIUS}}x… up to {{MAX_CHARACTER_SIZE}}x{{MAX_CHARACTER_SIZE}}.

Seeing farther is a trade, not a free upgrade. The tiles you must read grow
with the SQUARE of the radius — doubling it quadruples the grid, and an
autopilot run pays for that grid in tokens on every single turn — and the 2.5D
view has to stream and draw everything inside the new fog distance, so the
frame rate falls off the same way. The point is that you can choose when to pay:
widen your sight where the ground ahead decides your route, get the layout, then
narrow it again and travel cheaply on what you learned.

## Endpoints

| method and path | body | query | what it does |
| --- | --- | --- | --- |
{{ENDPOINTS}}

## Actions — moving

God mode moves by compass; character mode moves relative to its facing.
Diagonal steps slide: if the diagonal is blocked on one axis, you still move
along the other.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{MOVEMENT_ACTIONS}}

## Actions — your senses (character mode)

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{SENSES_ACTIONS}}

## Actions — building the world (god mode)

The world is generated by an ordered pipeline of nodes. Each node outputs a
field (numbers per tile), tiles (a tile id per cell), or points (tagged
markers); a node may consume the outputs of EARLIER nodes only. A display
binding maps a node into the world: tile layers stack in list order, elevation
shapes the ground, markers draw glyphs, prefabs stamp structures, creatures
spawn life, items float loot above the ground. Every act that edits echoes the full pipeline back, and every later
observation is regenerated from it.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{PIPELINE_ACTIONS}}

## Actions — the libraries (god mode)

Tiles, items, prefabs, creatures and characters are the vocabulary the pipeline
draws from. A node references them by id, so create the definition first, then
point a node at it.

An item is pixel art on a transparent background plus how it is drawn — a
billboard (the sprite extruded to a slight thickness, standing up or lying flat,
its rim painted with the edge color) or a floating cube painted face by face —
and how much room it takes in an inventory: 1x1, 1x2, 2x2, or any size up to
8x8. A character is a creature that additionally carries an inventory: a grid
whose slots can each be switched off or tagged, so a tagged slot only accepts
items carrying one of its tags, with a sprite layered underneath.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{LIBRARY_ACTIONS}}

## Actions — whole worlds (god mode)

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{WORLD_ACTIONS}}

## Example bodies

One per action that takes params:

{{EXAMPLES}}

## Failure codes

| code | meaning | recovery |
| --- | --- | --- |
{{FAILURES}}

## Node types you can add

Full param and input details: GET /api/v1/node-types.

| type | output | category | when to use |
| --- | --- | --- | --- |
{{NODE_TYPES}}

## Legend (current tileset)

{{LEGEND}}

Marker glyphs placed by the world's pipeline can also appear; each observation's
legend names every glyph visible in that observation.

## The loop

Observe, decide, act, repeat. Every act response carries a fresh observation,
so a simple loop needs only POST .../act. Nothing moves while you think: the
world only changes when someone acts on it.

## Autopilot runs

A run started through POST .../run drives the agent with an LLM. It gets one tool
per action above, plus these of its own:

| tool | what it does |
| --- | --- |
{{AUTOPILOT_TOOLS}}

Notes and scripts outlive the run, and both are repeated back in every
observation the model sees, along with what is left of the run's dollar budget.
A script is a list of these same actions — one per line, params as key=value,
optionally prefixed with "repeat N" — so it can do nothing an agent could not do
a step at a time. Scripts are checked against this mode's actions and their
params when they are written, not when they are run.
`;

export function buildApiDocs(tileset: ReadOnlyTileset): string {
  const filled = TEMPLATE.replace(/\{\{(\w+)\}\}/g, (_, key: string) =>
    placeholderValue(tileset, key),
  );
  const unfilled = filled.match(/\{\{\w+\}\}/);
  if (unfilled) throw new Error(`unfilled docs placeholder ${unfilled[0]}`);
  return filled;
}

export function everyAbility(): AbilitySpec[] {
  const modes: AbilityMode[] = ['god', 'character'];
  return modes.flatMap((mode) => abilitiesForMode(mode));
}

function placeholderValue(tileset: ReadOnlyTileset, key: string): string {
  if (key === 'GOD_SIZE') return String(GOD_VIEW_SIZE);
  if (key === 'CHARACTER_SIZE') return String(characterViewSize());
  if (key === 'SIGHT_RADIUS') return String(DEFAULT_CHARACTER_SIGHT_RADIUS_TILES);
  if (key === 'MIN_SIGHT_RADIUS') return String(MIN_CHARACTER_SIGHT_RADIUS_TILES);
  if (key === 'MAX_SIGHT_RADIUS') return String(MAX_CHARACTER_SIGHT_RADIUS_TILES);
  if (key === 'MAX_CHARACTER_SIZE') return String(characterViewSize(MAX_CHARACTER_SIGHT_RADIUS_TILES));
  if (key === 'ENDPOINTS') return endpointsTable();
  if (key === 'AUTOPILOT_TOOLS') return autopilotToolsTable();
  if (key === 'EXAMPLES') return examples();
  if (key === 'FAILURES') return failuresTable();
  if (key === 'NODE_TYPES') return nodeTypesTable();
  if (key === 'LEGEND') return legendBlock(tileset);
  return actionsTableFor(key);
}

const GROUP_OF_PLACEHOLDER: Readonly<Record<string, AbilityGroup>> = {
  MOVEMENT_ACTIONS: 'movement',
  SENSES_ACTIONS: 'senses',
  PIPELINE_ACTIONS: 'pipeline',
  LIBRARY_ACTIONS: 'library',
  WORLD_ACTIONS: 'world',
};

function actionsTableFor(key: string): string {
  const group = GROUP_OF_PLACEHOLDER[key];
  if (!group) throw new Error(`unknown docs placeholder ${key}`);
  return actionsTable(everyAbility().filter((spec) => spec.group === group));
}

function actionsTable(specs: readonly AbilitySpec[]): string {
  return specs
    .map(
      (spec) =>
        `| \`${spec.action}\` | ${paramsCell(spec)} | ${spec.humanControl} | ${spec.description} |`,
    )
    .join('\n');
}

function paramsCell(spec: AbilitySpec): string {
  const entries = Object.entries(spec.params);
  if (entries.length === 0) return '—';
  return entries
    .map(([name, param]) => `\`${name}\`${param.optional ? ' (optional)' : ''}: ${param.help}`)
    .join('; ');
}

function autopilotToolsTable(): string {
  return metaTools('god')
    .map((tool) => `| ${tool.name} | ${firstSentenceOf(tool.description)} |`)
    .join('\n');
}

function firstSentenceOf(description: string): string {
  const stop = description.indexOf('. ');
  return stop === -1 ? description.replace(/\.$/, '') : description.slice(0, stop);
}

function endpointsTable(): string {
  return allRoutes()
    .map(
      (route) =>
        `| ${route.method} /api/v1${route.path} | ${paramsCellOf(route.body)} | ${paramsCellOf(route.query)} | ${route.summary} |`,
    )
    .join('\n');
}

function paramsCellOf(params: Record<string, AbilityParamSpec>): string {
  const entries = Object.entries(params);
  if (entries.length === 0) return '—';
  return entries
    .map(([name, param]) => `\`${name}\`${param.optional ? ' (optional)' : ''}: ${param.help}`)
    .join('; ');
}

function examples(): string {
  return everyAbility()
    .filter((spec) => Object.keys(spec.params).length > 0)
    .map((spec) => `    ${JSON.stringify(spec.example)}`)
    .join('\n');
}

function failuresTable(): string {
  return FAILURES.map(
    (failure) => `| \`${failure.code}\` | ${failure.meaning} | ${failure.recovery} |`,
  ).join('\n');
}

function nodeTypesTable(): string {
  return allNodeTypes()
    .map(
      (def) =>
        `| \`${def.type}\` | ${typeof def.output === 'function' ? 'depends on params' : def.output} | ${def.category} | ${def.whenToUse} |`,
    )
    .join('\n');
}

function legendBlock(tileset: ReadOnlyTileset): string {
  const tiles = tileset
    .all()
    .map(
      (tile) =>
        `- '${tile.symbol}' = ${tile.name} (${tile.walkable ? 'you can walk here' : 'blocks you'})`,
    );
  return [
    "- '@' = you",
    "- ' ' = nothing generated here (in character mode, also: behind you, or fogged out past your sight radius)",
    "- '?' = unrecognized tile",
    ...tiles,
  ].join('\n');
}
