import { defaultTileId } from '@/features/asset-library/tiles/defaultTiles';
import type { ExamplePipeline } from './examplePipeline';

const TERRACE_LEVELS = 7;
const HEIGHT_SCALE = 14;
const DRY_FLOOR = 0;

export function mesaBadlands(): ExamplePipeline {
  return {
    name: 'mesa badlands',
    description:
      'A dry country of flat-topped buttes standing over a sand floor. Every mesa is the same stack of beds — pale sandstone banded with thin grey conglomerate under a dark hard cap — sliced into level benches, so the same stripes line up from one butte to the next across miles of empty air. Most cliffs are sealed walls; a third of the upward steps are unstepped ramps, and finding them is how you get anywhere. Scree collects along every riser and dry washes thread the floor between them.',
    state: {
      seed: 811,
      daylight: 1,
      nodes: [
        {
          id: 'bedrock',
          type: 'terrainNoise',
          label: 'bedrock relief',
          folder: 'the rock',
          comment:
            'The one source of shape in this world: broad rolling noise at basin scale. Everything a mesa is comes from slicing this surface, so it is kept smooth and low-frequency and the drama is added later by the terracing.',
          enabled: true,
          params: { scale: 0.012, style: 0, octaves: 6, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpX',
          type: 'noiseField',
          label: 'wander east-west',
          folder: 'the rock',
          comment:
            'Low-frequency noise used only as a sideways push. Without it the mesa rims are contour lines of the bedrock noise and read as machine-made ovals.',
          enabled: true,
          params: { scale: 0.015, octaves: 3 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpY',
          type: 'noiseField',
          label: 'wander north-south',
          folder: 'the rock',
          comment:
            'The same push on the other axis, seeded differently by virtue of being its own node, so the displacement is a real two-dimensional swirl rather than a diagonal smear.',
          enabled: true,
          params: { scale: 0.015, octaves: 3 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'folded',
          type: 'domainWarp',
          label: 'folded bedrock',
          folder: 'the rock',
          comment:
            'The bedrock read from a position that wanders by up to eighteen tiles. This happens before the terracing on purpose: warping a stepped field would interpolate across its risers and quietly turn every cliff into a staircase, so the contours are bent while they are still smooth and the steps are cut afterwards.',
          enabled: true,
          params: { strength: 18 },
          inputs: { source: 'bedrock', offsetX: 'warpX', offsetY: 'warpY' },
          display: { mode: 'hidden' },
        },
        {
          id: 'platform',
          type: 'hypsometricCurve',
          label: 'floor and platform',
          folder: 'the rock',
          comment:
            'Pushes the relief away from its middle into a broad low floor and a broad high platform with a short steep climb between them. That two-humped shape is what makes the terraces below bunch into cliffs a few tiles wide instead of spreading into an even flight of stairs across the whole map.',
          enabled: true,
          params: { seaLevel: 0.5, steepness: 12 },
          inputs: { source: 'folded' },
          display: { mode: 'hidden' },
        },
        {
          id: 'passes',
          type: 'terrainNoise',
          label: 'where the cliff is broken',
          folder: 'the rock',
          comment:
            'Noise at gully scale whose high ground marks the places a rockfall or a slumped bed left a way up. It never draws anything; it only tells the terracing where to leave the slope unstepped, which is the difference between a sealed plateau and one you can actually climb.',
          enabled: true,
          params: { scale: 0.045, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'benches',
          type: 'terraceField',
          label: 'stacked benches',
          folder: 'the rock',
          comment:
            'The node that makes this world what it is: the platform is snapped to seven levels, so every hillside becomes a flat bench ending in a vertical riser, and the same seven levels recur on every butte for miles. Where the pass noise runs high the original smooth slope is kept instead, leaving ramps through the cliffs. Every riser is two navigation levels and so is a sealed wall on its own; the passes are the only way up, and the threshold decides whether they link into routes or strand each bench. Run `bash scripts/runTool.sh probeTerrainProfile --world "mesa badlands"` after changing it: at 0.65 a walker starting on the basin floor reaches every one of the seven levels and 85% of the surrounding country.',
          enabled: true,
          params: { levels: TERRACE_LEVELS, passesAbove: 0.65 },
          inputs: { source: 'platform', passes: 'passes' },
          display: { mode: 'hidden' },
        },
        {
          id: 'filled',
          type: 'fillDepressions',
          label: 'drainable bedrock',
          folder: 'the washes',
          comment:
            'Runoff is routed over the smooth folded bedrock rather than the terraced surface, because a stepped world is all dead-flat benches and closed risers and water has nowhere to go on it. This floods the noise pits in that smooth surface so every drop can reach an outlet.',
          enabled: true,
          params: { seaLevel: DRY_FLOOR, maxFill: 0.1, windowRadius: 48 },
          inputs: { elevation: 'folded' },
          display: { mode: 'hidden' },
        },
        {
          id: 'flow',
          type: 'flowAccumulation',
          label: 'runoff',
          folder: 'the washes',
          comment:
            'Where the rain of the few storms a year collects. The full-flow catchment is small because a wash drains a stretch of badland floor, not a continent, and at this scale the short braided threads between the buttes still register as watercourses.',
          enabled: true,
          params: { seaLevel: DRY_FLOOR, catchmentScale: 800, convergence: 4, channelizeAbove: 20, fillPits: 0, windowRadius: 48 },
          inputs: { elevation: 'filled' },
          display: { mode: 'hidden' },
        },
        {
          id: 'washes',
          type: 'carveValleys',
          label: 'wash-cut ground',
          folder: 'the washes',
          comment:
            'The drainage cut back into the terraced rock: narrow, shallow, sharp-sided. This is the ground the world stands on. Drawn at fourteen tiles of relief so that a riser between two of the seven benches is exactly two tiles — one more than a body can pull itself up, which is what makes a cliff a wall — while the unstepped ramps stay a gentle grade you can walk.',
          enabled: true,
          params: { depth: 0.04, minFlow: 0.35, valleyWidth: 2 },
          inputs: { elevation: 'benches', flow: 'flow' },
          display: { mode: 'elevation', heightScale: HEIGHT_SCALE },
        },
        {
          id: 'slope',
          type: 'slopeField',
          label: 'steepness',
          folder: 'talus',
          comment:
            'How hard the ground falls away, measured one tile each way and geared so that a full terrace riser reads as 1 and everything gentler — a wash bank, a ramp — stays well below it. That is what keeps the scree on the cliffs instead of over the whole basin. Nothing but the talus and the brush read it.',
          enabled: true,
          params: { radius: 1, gain: 5 },
          inputs: { source: 'washes' },
          display: { mode: 'hidden' },
        },
        {
          id: 'floorBed',
          type: 'thresholdTiles',
          label: 'basin floor',
          folder: 'strata',
          comment:
            'The bottom of the section and the base coat for the whole world: packed red dirt, painted on both sides of the cut so no cell is ever left empty. Every band above only overrides part of it.',
          enabled: true,
          params: {
            threshold: 0,
            belowTile: defaultTileId('shore sand'),
            aboveTile: defaultTileId('shore sand'),
          },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'lowerSandstone',
          type: 'thresholdTiles',
          label: 'lower sandstone',
          folder: 'strata',
          comment:
            'First bench up, and a pale one: most of the open basin floor is this bed. Each band in this folder cuts at the midpoint below one of the seven terrace levels, so a band can never land halfway across a bench even where a wash has shaved a little off it, and each paints empty below so the beds underneath survive.',
          enabled: true,
          params: { threshold: 0.07, belowTile: -1, aboveTile: defaultTileId('gravel yard') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'redMudstone',
          type: 'thresholdTiles',
          label: 'red mudstone',
          folder: 'strata',
          comment: 'The first dark bed. Alternating a dark band with a pale one is what makes a hillside read as bedded rock at a distance rather than as a smooth ramp of dirt.',
          enabled: true,
          params: { threshold: 0.21, belowTile: -1, aboveTile: defaultTileId('shore sand') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'conglomerate',
          type: 'thresholdTiles',
          label: 'conglomerate ledge',
          folder: 'strata',
          comment: 'Grey cemented gravel: the one hard bed low in the section, which is why its bench so often stands out as a shelf ringing the foot of a butte.',
          enabled: true,
          params: { threshold: 0.36, belowTile: -1, aboveTile: defaultTileId('scree') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'sandstone',
          type: 'thresholdTiles',
          label: 'pale sandstone',
          folder: 'strata',
          comment: 'The bright band at mid-height, visible from across the basin and the easiest way to tell at a glance that two buttes a mile apart are the same rock.',
          enabled: true,
          params: { threshold: 0.5, belowTile: -1, aboveTile: defaultTileId('shore sand') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'upperRedBed',
          type: 'thresholdTiles',
          label: 'upper red bed',
          folder: 'strata',
          comment: 'The red mudstone returns above the sandstone. The section repeats itself going up, so a tall butte shows the same dark-pale-dark rhythm twice.',
          enabled: true,
          params: { threshold: 0.64, belowTile: -1, aboveTile: defaultTileId('gravel yard') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'buffSiltstone',
          type: 'thresholdTiles',
          label: 'buff siltstone',
          folder: 'strata',
          comment: 'Soft buff silt directly under the cap. It weathers back faster than the rock above it, which is why rims collapse and why the caprock ends in an overhanging edge.',
          enabled: true,
          params: { threshold: 0.79, belowTile: -1, aboveTile: defaultTileId('shore sand') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'caprock',
          type: 'thresholdTiles',
          label: 'caprock',
          folder: 'strata',
          comment:
            'The hard grey lid on the highest bench, the only bed in the section that is grey. Only ground that reached the top terrace gets it, so it doubles as the mark of which buttes are full height.',
          enabled: true,
          params: { threshold: 0.93, belowTile: -1, aboveTile: defaultTileId('packed dirt') },
          inputs: { source: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'dryWashes',
          type: 'riverFromFlow',
          label: 'dry washes',
          folder: 'the washes',
          comment:
            'The channels themselves, floored with the same loose stone the cliffs shed, because a wash bottom is talus that has been carried downhill and rolled. The threshold is high so only the trunk washes show and the hillside gullies stay bare rock — a wash is a road across the badlands, and there should not be one everywhere.',
          enabled: true,
          params: { minFlow: 0.8, maxWidth: 3, seaLevel: DRY_FLOOR, riverTile: defaultTileId('scree') },
          inputs: { flow: 'flow', elevation: 'washes' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'talus',
          type: 'biomeBands',
          label: 'talus and cliff faces',
          folder: 'talus',
          comment:
            'Painted last so it wins over the strata, and masked by the same steepness it reads, so it exists only on the risers and the broken ground at their feet. The slope gain feeding it is what decides how much of the country it claims: at 14 it took nearly half the surface and the world read as grey rubble, so it is set to 5, which leaves it on the risers where it belongs: everything gentler is left empty for the beds beneath. There is no water and no snow in this world, so the water bands are pushed below every possible height and the snow band is given the same scree as the rock band, which leaves the node doing one job — loose stone wherever rock is falling.',
          enabled: true,
          params: {
            seaLevel: 0,
            deepDrop: 0,
            shoreBand: 0,
            rockAbove: 0.9,
            snowLine: 1,
            regionAtLeast: 0.9,
            deepTile: -1,
            waterTile: -1,
            shoreTile: -1,
            groundTile: -1,
            rockTile: defaultTileId('scree'),
            snowTile: defaultTileId('scree'),
          },
          inputs: { elevation: 'washes', steepness: 'slope', region: 'slope' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'brush',
          type: 'scatterPoints',
          label: 'desert brush',
          folder: 'talus',
          comment:
            'The only living thing here, and it grows only on flat ground: benches and floor, never a riser. Sparse enough that the eye still reads bare rock.',
          enabled: true,
          params: { density: 0.006, maskAtLeast: 0, maskAtMost: 0.12 },
          inputs: { mask: 'slope' },
          display: { mode: 'markers', tileId: defaultTileId('hazel bush'), glyph: '%', color: '#7a7a48' },
        },
        {
          id: 'wake',
          type: 'landmarkPoint',
          label: 'where you wake',
          folder: 'where you wake',
          comment: 'The one hand-placed thing in the world: the floor of the basin at the origin, looking up.',
          enabled: true,
          params: { x: 0, y: 0 },
          inputs: {},
          display: { mode: 'markers', tileId: -1, glyph: '✦', color: '#ffd27f' },
        },
      ],
    },
  };
}
