import { allNodeTypes } from '../procgen/nodeRegistry';
import type { Tileset } from '../world/tiles/tileset';
import { CHARACTER_VIEW_SIZE, GOD_VIEW_SIZE } from './observation';
import { FAILURES } from './failures';
import { verbsForMode, type VerbSpec } from './controls';

const TEMPLATE = `# Procgen world — agent API

You are an agent in an infinite, procedurally generated world. Everything you
can know about the world arrives as an ASCII grid plus a legend; everything you
can do goes through one action verb per request. A human playing this world in
agent mode sees exactly the text you receive — nothing more.

## Coordinate system (read this first)

- x grows EAST, y grows SOUTH. The grid is always drawn north-up; it never
  rotates.
- Every observation tells you its own top-left origin: row r, col c of the grid
  is world tile (origin_x + c, origin_y + r).
- You are the '@' at the center of the grid.

## Modes

An agent is created in one of two modes and stays in it for life.

- **god** — a {{GOD_SIZE}}x{{GOD_SIZE}} window centered on you. You see every
  generated tile in the window, and your facing is stated in the observation.
  You move by absolute compass steps, and you can REBUILD THE WORLD: the
  editing verbs below create and manipulate the procgen node pipeline that
  generates every tile everyone sees.
- **character** — a {{CHARACTER_SIZE}}x{{CHARACTER_SIZE}} window centered on
  you, but only the tiles IN FRONT of you are drawn; the half of the grid
  behind you is blank. The blank side is how you know which way you face — the
  observation never states it. You move relative to your facing and turn in
  45-degree steps. Characters cannot edit the world.

## Endpoints

| method and path | body | what it does |
| --- | --- | --- |
| GET /api/v1/docs | — | this document |
| POST /api/v1/agents | {"mode": "god" or "character", "name": optional} | create an agent; responds with its id and urls |
| GET /api/v1/agents | — | list agents |
| GET /api/v1/agents/{id} | — | the agent's current state |
| DELETE /api/v1/agents/{id} | — | remove the agent |
| GET /api/v1/agents/{id}/observe?format=json or text | — | a fresh observation |
| POST /api/v1/agents/{id}/act | {"action": "...", ...params} | perform one action; responds with the outcome and a fresh observation |
| GET /api/v1/pipeline | — | the current node pipeline: every node with id, type, params, wiring, display |
| GET /api/v1/node-types | — | the catalog of node types god agents can add, every param and input explained |
| GET /api/v1/prefabs | — | the prefab library: structures a points node can stamp into the world via set_display |
| GET /api/v1/creatures | — | the creature library: creatures a points node can spawn via set_display |
| POST /api/v1/agents/{id}/run | {"goal": "...", "model": optional, "max_steps": optional, "anthropic_api_key": optional} | start an autopilot run that drives this agent with an LLM |
| POST /api/v1/agents/{id}/stop | — | stop the autopilot run |
| GET /api/v1/agents/{id}/transcript?after=seq | — | the autopilot transcript |

## Actions — god mode, moving

| action | params | human control | what it does |
| --- | --- | --- | --- |
{{GOD_MOVE_ACTIONS}}

Diagonal steps slide: if the diagonal is blocked on one axis, you still move
along the other.

## Actions — god mode, building the world

The world is generated by an ordered pipeline of nodes. Each node outputs a
field (numbers per tile), tiles (a tile id per cell), or points (tagged
markers); a node may consume the outputs of EARLIER nodes only. A display
binding maps a node into the world: tile layers stack in list order, elevation
shapes the ground, markers draw glyphs. Every act that edits echoes the full
pipeline back, and the world in every later observation is regenerated from it.

| action | params | human control | what it does |
| --- | --- | --- | --- |
{{GOD_EDIT_ACTIONS}}

Example bodies, one per verb:

{{EDIT_EXAMPLES}}

## Actions — character mode

| action | params | human control | what it does |
| --- | --- | --- | --- |
{{CHARACTER_ACTIONS}}

## Failure codes

| code | meaning | recovery |
| --- | --- | --- |
{{FAILURES}}

## Node types you can add

Full param and input details: GET /api/v1/node-types.

| type | output | category | when to use |
| --- | --- | --- | --- |
{{NODE_TYPES}}

## Legend (current tileset)

{{LEGEND}}

Marker glyphs placed by the world's pipeline can also appear; each observation's
legend names every glyph visible in that observation.

## The loop

Observe, decide, act, repeat. Every act response carries a fresh observation,
so a simple loop needs only POST .../act. Nothing moves while you think: the
world only changes when someone acts on it — or when a god rebuilds it.
`;

export function buildApiDocs(tileset: Tileset): string {
  const filled = TEMPLATE.replace(/\{\{(\w+)\}\}/g, (_, key: string) => placeholderValue(tileset, key));
  const unfilled = filled.match(/\{\{\w+\}\}/);
  if (unfilled) throw new Error(`unfilled docs placeholder ${unfilled[0]}`);
  return filled;
}

function placeholderValue(tileset: Tileset, key: string): string {
  if (key === 'GOD_SIZE') return String(GOD_VIEW_SIZE);
  if (key === 'CHARACTER_SIZE') return String(CHARACTER_VIEW_SIZE);
  if (key === 'GOD_MOVE_ACTIONS') return actionsTable(godVerbs('movement'));
  if (key === 'GOD_EDIT_ACTIONS') return actionsTable(godVerbs('editing'));
  if (key === 'EDIT_EXAMPLES') return editExamples();
  if (key === 'CHARACTER_ACTIONS') return actionsTable(verbsForMode('character'));
  if (key === 'FAILURES') return failuresTable();
  if (key === 'NODE_TYPES') return nodeTypesTable();
  if (key === 'LEGEND') return legendBlock(tileset);
  throw new Error(`unknown docs placeholder ${key}`);
}

function godVerbs(group: 'movement' | 'editing'): readonly VerbSpec[] {
  return verbsForMode('god').filter((verb) => verb.group === group);
}

function actionsTable(verbs: readonly VerbSpec[]): string {
  return verbs
    .map(
      (verb) =>
        `| \`${verb.action}\` | ${paramsCell(verb)} | ${verb.humanControl} | ${verb.description} |`,
    )
    .join('\n');
}

function paramsCell(verb: VerbSpec): string {
  const entries = Object.entries(verb.params);
  if (entries.length === 0) return '—';
  return entries.map(([name, description]) => `\`${name}\`: ${description}`).join('; ');
}

function editExamples(): string {
  return godVerbs('editing')
    .map((verb) => `    ${JSON.stringify(verb.example)}`)
    .join('\n');
}

function failuresTable(): string {
  return FAILURES.map(
    (failure) => `| \`${failure.code}\` | ${failure.meaning} | ${failure.recovery} |`,
  ).join('\n');
}

function nodeTypesTable(): string {
  return allNodeTypes()
    .map(
      (def) =>
        `| \`${def.type}\` | ${typeof def.output === 'function' ? 'depends on params' : def.output} | ${def.category} | ${def.whenToUse} |`,
    )
    .join('\n');
}

function legendBlock(tileset: Tileset): string {
  const tiles = tileset
    .all()
    .map(
      (tile) =>
        `- '${tile.symbol}' = ${tile.name} (${tile.walkable ? 'you can walk here' : 'blocks you'})`,
    );
  return [
    "- '@' = you",
    "- ' ' = nothing generated here (in character mode, also: behind you)",
    "- '?' = unrecognized tile",
    ...tiles,
  ].join('\n');
}
