import '../abilities/index';
import { abilitiesForMode } from '../abilities/abilityRegistry';
import type { AbilityGroup, AbilityMode, AbilitySpec } from '../abilities/ability';
import { allNodeTypes } from '../procgen/nodeRegistry';
import type { ReadOnlyTileset } from '../app/readOnlyLibraries';
import {
  CHARACTER_SIGHT_RADIUS_TILES,
  CHARACTER_VIEW_SIZE,
} from '../world/vision/characterSight';
import { GOD_VIEW_SIZE } from './observation';
import { FAILURES } from './failures';

const TEMPLATE = `# Procgen world — agent API

You are an agent in an infinite, procedurally generated world. Everything you
can know about the world arrives as an ASCII grid plus a legend; everything you
can do goes through one action per request.

**Every ability in this application is one of the actions below.** The human
sitting at the browser has no powers you lack: their buttons, knobs and drags
call exactly the same actions with the same validation, and each action's row
names the control they would use. A human in an agent view mode reads exactly
the text you receive — nothing more.

## Coordinate system (read this first)

- x grows EAST, y grows SOUTH. The grid is always drawn north-up; it never
  rotates.
- Every observation tells you its own top-left origin: row r, col c of the grid
  is world tile (origin_x + c, origin_y + r).
- You are the '@' at the center of the grid.

## Modes

An agent is created in one of two modes and stays in it for life.

- **god** — a {{GOD_SIZE}}x{{GOD_SIZE}} window centered on you. You see every
  generated tile in the window, and your facing is stated in the observation.
  You move by absolute compass steps, and you can REBUILD THE WORLD: the
  pipeline, library and world actions below are the whole world editor.
- **character** — a {{CHARACTER_SIZE}}x{{CHARACTER_SIZE}} window centered on
  you, but you only see the half-disc in front of you: tiles behind you are
  blank, and so is everything past your {{SIGHT_RADIUS}}-tile sight radius,
  which is why the corners of the grid are blank too. The blank half is how you
  know which way you face — the observation never states it. That half-disc is
  exactly the ground the 2.5D character view renders before its fog closes in,
  so a human playing that view knows no more of the world than you do. You move
  relative to your facing and turn in 45-degree steps. Characters can only
  move.

## Endpoints

| method and path | body | what it does |
| --- | --- | --- |
| GET /api/v1/docs | — | this document |
| POST /api/v1/agents | {"mode": "god" or "character", "name": optional} | create an agent; responds with its id and urls |
| GET /api/v1/agents | — | list agents |
| GET /api/v1/agents/{id} | — | the agent's current state |
| DELETE /api/v1/agents/{id} | — | remove the agent |
| GET /api/v1/agents/{id}/observe?format=json or text | — | a fresh observation |
| POST /api/v1/agents/{id}/act | {"action": "...", ...params} | perform one action; responds with the outcome and a fresh observation |
| GET /api/v1/pipeline | — | the current node pipeline: every node with id, type, params, wiring, display |
| GET /api/v1/node-types | — | the catalog of node types you can add, every param and input explained |
| GET /api/v1/tiles | — | the tileset: what every glyph in an observation means |
| GET /api/v1/prefabs | — | the prefab library: structures a points node can stamp |
| GET /api/v1/creatures | — | the creature library: creatures a points node can spawn |
| GET /api/v1/templates | — | saved groups of wired nodes you can stamp in |
| GET /api/v1/presets | — | whole worlds you can load |
| POST /api/v1/agents/{id}/run | {"goal": "...", "model": optional, "max_steps": optional, "anthropic_api_key": optional} | start an autopilot run that drives this agent with an LLM |
| POST /api/v1/agents/{id}/stop | — | stop the autopilot run |
| GET /api/v1/agents/{id}/transcript?after=seq | — | the autopilot transcript |

## Actions — moving

God mode moves by compass; character mode moves relative to its facing.
Diagonal steps slide: if the diagonal is blocked on one axis, you still move
along the other.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{MOVEMENT_ACTIONS}}

## Actions — building the world (god mode)

The world is generated by an ordered pipeline of nodes. Each node outputs a
field (numbers per tile), tiles (a tile id per cell), or points (tagged
markers); a node may consume the outputs of EARLIER nodes only. A display
binding maps a node into the world: tile layers stack in list order, elevation
shapes the ground, markers draw glyphs, prefabs stamp structures, creatures
spawn life. Every act that edits echoes the full pipeline back, and every later
observation is regenerated from it.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{PIPELINE_ACTIONS}}

## Actions — the libraries (god mode)

Tiles, prefabs and creatures are the vocabulary the pipeline draws from. A node
references them by id, so create the definition first, then point a node at it.

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{LIBRARY_ACTIONS}}

## Actions — whole worlds (god mode)

| action | params | the human control | what it does |
| --- | --- | --- | --- |
{{WORLD_ACTIONS}}

## Example bodies

One per action that takes params:

{{EXAMPLES}}

## Failure codes

| code | meaning | recovery |
| --- | --- | --- |
{{FAILURES}}

## Node types you can add

Full param and input details: GET /api/v1/node-types.

| type | output | category | when to use |
| --- | --- | --- | --- |
{{NODE_TYPES}}

## Legend (current tileset)

{{LEGEND}}

Marker glyphs placed by the world's pipeline can also appear; each observation's
legend names every glyph visible in that observation.

## The loop

Observe, decide, act, repeat. Every act response carries a fresh observation,
so a simple loop needs only POST .../act. Nothing moves while you think: the
world only changes when someone acts on it.
`;

export function buildApiDocs(tileset: ReadOnlyTileset): string {
  const filled = TEMPLATE.replace(/\{\{(\w+)\}\}/g, (_, key: string) =>
    placeholderValue(tileset, key),
  );
  const unfilled = filled.match(/\{\{\w+\}\}/);
  if (unfilled) throw new Error(`unfilled docs placeholder ${unfilled[0]}`);
  return filled;
}

export function everyAbility(): AbilitySpec[] {
  const modes: AbilityMode[] = ['god', 'character'];
  return modes.flatMap((mode) => abilitiesForMode(mode));
}

function placeholderValue(tileset: ReadOnlyTileset, key: string): string {
  if (key === 'GOD_SIZE') return String(GOD_VIEW_SIZE);
  if (key === 'CHARACTER_SIZE') return String(CHARACTER_VIEW_SIZE);
  if (key === 'SIGHT_RADIUS') return String(CHARACTER_SIGHT_RADIUS_TILES);
  if (key === 'EXAMPLES') return examples();
  if (key === 'FAILURES') return failuresTable();
  if (key === 'NODE_TYPES') return nodeTypesTable();
  if (key === 'LEGEND') return legendBlock(tileset);
  return actionsTableFor(key);
}

const GROUP_OF_PLACEHOLDER: Readonly<Record<string, AbilityGroup>> = {
  MOVEMENT_ACTIONS: 'movement',
  PIPELINE_ACTIONS: 'pipeline',
  LIBRARY_ACTIONS: 'library',
  WORLD_ACTIONS: 'world',
};

function actionsTableFor(key: string): string {
  const group = GROUP_OF_PLACEHOLDER[key];
  if (!group) throw new Error(`unknown docs placeholder ${key}`);
  return actionsTable(everyAbility().filter((spec) => spec.group === group));
}

function actionsTable(specs: readonly AbilitySpec[]): string {
  return specs
    .map(
      (spec) =>
        `| \`${spec.action}\` | ${paramsCell(spec)} | ${spec.humanControl} | ${spec.description} |`,
    )
    .join('\n');
}

function paramsCell(spec: AbilitySpec): string {
  const entries = Object.entries(spec.params);
  if (entries.length === 0) return '—';
  return entries
    .map(([name, param]) => `\`${name}\`${param.optional ? ' (optional)' : ''}: ${param.help}`)
    .join('; ');
}

function examples(): string {
  return everyAbility()
    .filter((spec) => Object.keys(spec.params).length > 0)
    .map((spec) => `    ${JSON.stringify(spec.example)}`)
    .join('\n');
}

function failuresTable(): string {
  return FAILURES.map(
    (failure) => `| \`${failure.code}\` | ${failure.meaning} | ${failure.recovery} |`,
  ).join('\n');
}

function nodeTypesTable(): string {
  return allNodeTypes()
    .map(
      (def) =>
        `| \`${def.type}\` | ${typeof def.output === 'function' ? 'depends on params' : def.output} | ${def.category} | ${def.whenToUse} |`,
    )
    .join('\n');
}

function legendBlock(tileset: ReadOnlyTileset): string {
  const tiles = tileset
    .all()
    .map(
      (tile) =>
        `- '${tile.symbol}' = ${tile.name} (${tile.walkable ? 'you can walk here' : 'blocks you'})`,
    );
  return [
    "- '@' = you",
    "- ' ' = nothing generated here (in character mode, also: behind you, or fogged out past your sight radius)",
    "- '?' = unrecognized tile",
    ...tiles,
  ].join('\n');
}
