export const PERSISTED_UI_KEYS = {
  panelWidths: 'panel.widths',
  collapsedPanels: 'panel.collapsed',
  librarySelection: 'library.selection',
  runningWorld: 'library.running',
  openLibraryFolders: 'library.openFolders',
  openAssetFolders: 'library.openAssetFolders',
  libraryViewMode: 'library.viewMode',
  openTileArt: 'assets.openTileArt',
  openCreaturePanels: 'assets.openCreaturePanels',
  openItemPanels: 'assets.openItemPanels',
  openInventoryBackdrops: 'assets.openInventoryBackdrops',
  openCulturePanels: 'assets.openCulturePanels',
  hintsVisible: 'ui.hintsVisible',
  collapsedNodeCards: 'procgen.collapsedNodeCards',
  collapsedNodeFolders: 'procgen.collapsedNodeFolders',
  performancePanelOpen: 'world.performancePanelOpen',
  worldsColumns: 'worlds.columns',
  worldsRows: 'worlds.rows',
  worldsZoom: 'worlds.zoom',
  worldsCamera: 'worlds.camera',
} as const;
