import type { ExamplePipeline } from './examplePipeline';

export function emberMarches(): ExamplePipeline {
  return {
    name: 'the ember marches',
    description:
      'Walk east and the world burns. In the green west the rivers run with water past fens, cottages and hedge-walled labyrinth wards; at the frontier stands a burnt forest and a broken line of warding stones; beyond it the same rivers run as lava through ashlands where the wards are scorched, breached, and still patrolled by sentries who never got the order to stand down. Every creature keeps to its own country: deer shelter inside the overgrown wards, herons stalk the fens, ash hounds hunt the far east, and ember wisps drift along the molten rivers.',
    state: {
      seed: 4242,
      nodes: [
        {
          id: 'n1',
          type: 'tectonicUplift',
          label: 'plates',
          folder: 'bones of the land',
          comment:
            'One set of continents under both countries — the point of this world is that the land is the same on either side of the emberline; only what happened to it differs.',
          enabled: true,
          params: {
            plateSize: 288,
            oceanFraction: 0.5,
            beltWidth: 56,
            rangeHeight: 0.3,
            landHeight: 0.58,
            basinDepth: 0.32,
          },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n2',
          type: 'terrainNoise',
          label: 'warp x',
          folder: 'bones of the land',
          comment: 'East-west displacement for the warp that bends plate edges into coastlines.',
          enabled: true,
          params: { scale: 0.004, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n3',
          type: 'terrainNoise',
          label: 'warp y',
          folder: 'bones of the land',
          comment: 'The north-south half of the displacement, at a slightly different scale so the axes stay independent.',
          enabled: true,
          params: { scale: 0.0045, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n4',
          type: 'domainWarp',
          label: 'warped plates',
          folder: 'bones of the land',
          comment: 'Straight plate bisectors become headlands, bays and island arcs.',
          enabled: true,
          params: { strength: 90 },
          inputs: { source: 'n1', offsetX: 'n2', offsetY: 'n3' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n5',
          type: 'terrainNoise',
          label: 'rolling detail',
          folder: 'bones of the land',
          comment: 'Hills and coastal wobble so the marches are not billiard-flat.',
          enabled: true,
          params: { scale: 0.02, style: 0, octaves: 5, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n6',
          type: 'blendFields',
          label: 'rolling relief',
          folder: 'bones of the land',
          comment: 'A light pass of hills over the warped plates — texture, not competition.',
          enabled: true,
          params: { weight: 0.18 },
          inputs: { a: 'n4', b: 'n5', mask: null },
          display: { mode: 'hidden' },
        },
        {
          id: 'n7',
          type: 'hypsometricCurve',
          label: 'basins & platform',
          folder: 'bones of the land',
          comment:
            'Deep basins and a low land platform. This uneroded field is the reference the lava rivers later measure carving against, so it must stay untouched by erosion.',
          enabled: true,
          params: { seaLevel: 0.5, steepness: 9 },
          inputs: { source: 'n6' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n8',
          type: 'flowAccumulation',
          label: 'drainage',
          folder: 'water that remembers',
          comment:
            'One drainage network for the whole world. West of the emberline it will be dressed as water, east as lava — the river remembers its course even after it catches fire.',
          enabled: true,
          params: { seaLevel: 0.5, catchmentScale: 3000, fillPits: 1, windowRadius: 40 },
          inputs: { elevation: 'n7' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n9',
          type: 'carveValleys',
          label: 'eroded terrain',
          folder: 'water that remembers',
          comment:
            'The terrain everything stands on: valleys cut in proportion to the water they carry. The taper also digs the banks the lava rivers will glow through.',
          enabled: true,
          params: { depth: 0.08, minFlow: 0.4, valleyWidth: 6 },
          inputs: { elevation: 'n7', flow: 'n8' },
          display: { mode: 'elevation', heightScale: 7 },
        },
        {
          id: 'n10',
          type: 'slopeField',
          label: 'steepness',
          folder: 'water that remembers',
          comment: 'Grade of the hillsides, so both countries trade soil for bare rock on their cliffs.',
          enabled: true,
          params: { radius: 3, gain: 12 },
          inputs: { source: 'n9' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n11',
          type: 'coastDistance',
          label: 'coast distance',
          folder: 'water that remembers',
          comment: 'Shoreline distance for even-width beaches, and later the band the fens are cut from.',
          enabled: true,
          params: { seaLevel: 0.5, range: 32 },
          inputs: { elevation: 'n7' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n12',
          type: 'customScript',
          label: 'script: emberline',
          folder: 'the emberline',
          comment:
            'The gradient this world hinges on: char as a function of world X alone. Fully green west of x = −768, fully burnt east of x = +768, so walking east is walking into the fire that took half the marches.',
          enabled: true,
          params: { outputKind: 'field', code: EMBERLINE_SCRIPT },
          inputs: { a: null, b: null },
          display: { mode: 'hidden' },
        },
        {
          id: 'n13',
          type: 'terrainNoise',
          label: 'ember wobble',
          folder: 'the emberline',
          comment: 'Fire is not a ruler: this bends the frontier so the burnt edge meanders and bulges.',
          enabled: true,
          params: { scale: 0.012, style: 0, octaves: 3, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n14',
          type: 'blendFields',
          label: 'wobbled emberline',
          folder: 'the emberline',
          comment: 'A fifth of wobble is enough — the gradient must stay in charge or the two countries dissolve into each other.',
          enabled: true,
          params: { weight: 0.22 },
          inputs: { a: 'n12', b: 'n13', mask: null },
          display: { mode: 'hidden' },
        },
        {
          id: 'n15',
          type: 'hypsometricCurve',
          label: 'ash switch',
          folder: 'the emberline',
          comment: 'The curve as a switch: near 1 where char passes 0.62, near 0 in the green — the single line the ashfall biome, the lava and the hounds all obey.',
          enabled: true,
          params: { seaLevel: 0.62, steepness: 30 },
          inputs: { source: 'n14' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n16',
          type: 'hypsometricCurve',
          label: 'land switch',
          folder: 'the emberline',
          comment: 'Near 1 on dry ground, near 0 at sea — the sea never burns, and nothing spawns in the water.',
          enabled: true,
          params: { seaLevel: 0.52, steepness: 30 },
          inputs: { source: 'n9' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n17',
          type: 'constantField',
          label: 'one',
          folder: 'the emberline',
          comment: 'A constant 1, so the subtractions below can flip switches the other way around.',
          enabled: true,
          params: { value: 1 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n18',
          type: 'combineFields',
          label: 'green switch',
          folder: 'the emberline',
          comment: '1 minus the ash switch: high wherever the fire never reached.',
          enabled: true,
          params: { operation: 1, clamp: 1 },
          inputs: { a: 'n17', b: 'n15' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n19',
          type: 'customScript',
          label: 'script: ward lots',
          folder: 'the wards',
          comment:
            'Which 192-tile lots hold a ward. The span matches the labyrinth below exactly — 6 chunks of 32 — so every warded lot contains one complete self-contained maze, never a fragment of a neighboring one.',
          enabled: true,
          params: { outputKind: 'field', code: WARD_LOTS_SCRIPT },
          inputs: { a: null, b: null },
          display: { mode: 'hidden' },
        },
        {
          id: 'n20',
          type: 'combineFields',
          label: 'wards on land',
          folder: 'the wards',
          comment: 'Ward lots gated to dry ground — where a lot runs into the sea, the water keeps its claim and the maze drowns.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n19', b: 'n16' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n21',
          type: 'combineFields',
          label: 'the open wilds',
          folder: 'the wards',
          comment:
            '1 minus the wards: the region every biome paints. Inside warded land the biomes leave the cells empty, which is exactly where the maze below shows through.',
          enabled: true,
          params: { operation: 1, clamp: 1 },
          inputs: { a: 'n17', b: 'n20' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n22',
          type: 'mazeChunk',
          label: 'the wards',
          folder: 'the wards',
          comment:
            'The labyrinth itself, hedge walls over worn processional paths, one maze spanning each 6-chunk lot. It carves everywhere, but the biomes above bury it outside the warded lots. Two doors per edge and a little braid keep every ward walkable from the wilds.',
          enabled: true,
          params: {
            corridor: 3,
            wall: 1,
            mazeChunks: 6,
            carver: 0,
            braid: 0.25,
            doorsPerEdge: 2,
            wallTile: 24,
            floorTile: 8,
          },
          inputs: {},
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n23',
          type: 'customScript',
          label: 'script: scorch & breach',
          folder: 'the wards',
          comment:
            'What the fire did to the eastern wards: hedges become scorched stone, a third of every wall crumbles into ash-filled breaches, and the old paths vanish under ash. West of the emberline it paints nothing, leaving the hedges green.',
          enabled: true,
          params: { outputKind: 'tiles', code: SCORCH_AND_BREACH_SCRIPT },
          inputs: { a: 'n22', b: 'n14' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n24',
          type: 'biomeBands',
          label: 'the green march',
          folder: 'two countries',
          comment:
            'The unburnt world and the base coat: sea, sand shores, grass, bare rock on the steeps. It paints every cell outside warded land — including the whole ashfall, which the next biome overpaints.',
          enabled: true,
          params: {
            seaLevel: 0.5,
            deepDrop: 0.06,
            shoreBand: 0.05,
            rockAbove: 0.45,
            snowLine: 1,
            regionAtLeast: 0.5,
            deepTile: 5,
            waterTile: 0,
            shoreTile: 1,
            groundTile: 2,
            rockTile: 4,
            snowTile: 7,
          },
          inputs: { elevation: 'n9', steepness: 'n10', shoreDistance: 'n11', region: 'n21' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n25',
          type: 'combineFields',
          label: 'ash & open',
          folder: 'two countries',
          comment: 'The ashfall claims cells that are both east of the emberline and outside warded land.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n15', b: 'n21' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n26',
          type: 'biomeBands',
          label: 'the ashfall',
          folder: 'two countries',
          comment:
            'The same land after the fire: ash where grass would grow, gravel where beaches would lie, and the sea kept as water — the one thing on this side that did not burn. The region cut sits a little under the green march\'s so the ash wins the fractional slivers along drowned ward edges.',
          enabled: true,
          params: {
            seaLevel: 0.5,
            deepDrop: 0.06,
            shoreBand: 0.04,
            rockAbove: 0.5,
            snowLine: 1,
            regionAtLeast: 0.45,
            deepTile: 5,
            waterTile: 0,
            shoreTile: 9,
            groundTile: 22,
            rockTile: 4,
            snowTile: 7,
          },
          inputs: { elevation: 'n9', steepness: 'n10', shoreDistance: 'n11', region: 'n25' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n27',
          type: 'terrainNoise',
          label: 'fen clumps',
          folder: 'two countries',
          comment: 'Billowed continental-scale blobs deciding which stretches of the green coast drown into fen instead of keeping their beaches.',
          enabled: true,
          params: { scale: 0.008, style: 2, octaves: 3, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'n28',
          type: 'combineFields',
          label: 'green fens',
          folder: 'two countries',
          comment: 'Fen clumps gated to the green side — the ashfall coast is gravel, never marsh.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n27', b: 'n18' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n29',
          type: 'combineFields',
          label: 'fen country',
          folder: 'two countries',
          comment: 'And gated outside the wards, so no marsh creeps over a ward that runs down to the sea.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n28', b: 'n21' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n30',
          type: 'biomeBands',
          label: 'the drowning fens',
          folder: 'two countries',
          comment:
            'A biome used as a single-band painter: every tile empty except the shore, so all it paints is a wide marsh strip along the fen-country coastline, cut from coast distance so it keeps an even depth.',
          enabled: true,
          params: {
            seaLevel: 0.5,
            deepDrop: 0,
            shoreBand: 0.1,
            rockAbove: 1,
            snowLine: 1,
            regionAtLeast: 0.42,
            deepTile: -1,
            waterTile: -1,
            shoreTile: 10,
            groundTile: -1,
            rockTile: -1,
            snowTile: -1,
          },
          inputs: { elevation: 'n9', steepness: null, shoreDistance: 'n11', region: 'n29' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n31',
          type: 'riverFromFlow',
          label: 'rivers of water',
          folder: 'rivers of water & fire',
          comment:
            'The drainage dressed as water, painted over both countries — streams run freely through the hedge wards, and in the east the molten layer above will swallow all but the youngest trickles.',
          enabled: true,
          params: { minFlow: 0.55, maxWidth: 4, seaLevel: 0.5, riverTile: 0 },
          inputs: { flow: 'n8', elevation: 'n9' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n32',
          type: 'combineFields',
          label: 'carved depth',
          folder: 'rivers of water & fire',
          comment: 'Uneroded minus eroded terrain: nonzero exactly where the rivers dug their valleys.',
          enabled: true,
          params: { operation: 1, clamp: 1 },
          inputs: { a: 'n7', b: 'n9' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n33',
          type: 'combineFields',
          label: 'molten carve',
          folder: 'rivers of water & fire',
          comment: 'The carved band gated east of the emberline — the stretch of every valley that runs molten.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n32', b: 'n15' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n34',
          type: 'thresholdTiles',
          label: 'rivers of fire',
          folder: 'rivers of water & fire',
          comment:
            'Lava wherever the eastern valleys are carved deep enough, overpainting the water below it. The same channel crosses the frontier and changes state — follow any river east and watch it catch.',
          enabled: true,
          params: { threshold: 0.03, belowTile: -1, aboveTile: 21 },
          inputs: { source: 'n33' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n35',
          type: 'combineFields',
          label: 'char on land',
          folder: 'the frontier',
          comment: 'The emberline gradient gated to dry ground — its bands are the frontier habitats.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n14', b: 'n16' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n36',
          type: 'scatterPoints',
          label: 'the burnt forest',
          folder: 'the frontier',
          comment:
            'A strip of dead trees where the fire stopped — the woods that burned standing and never fell. Cross it and you know which country you are entering.',
          enabled: true,
          params: { density: 0.04, maskAtLeast: 0.55, maskAtMost: 0.68 },
          inputs: { mask: 'n35' },
          display: { mode: 'markers', tileId: 25, glyph: '†', color: '#342d28' },
        },
        {
          id: 'n37',
          type: 'scatterPoints',
          label: 'the warding stones',
          folder: 'the frontier',
          comment:
            'Stone circles in a dotted line exactly along the char 0.5 contour: the line someone once held, and the fire respected — mostly. They are the oldest things in the marches.',
          enabled: true,
          params: { density: 0.0005, maskAtLeast: 0.5, maskAtMost: 0.56 },
          inputs: { mask: 'n35' },
          display: { mode: 'pieces', pieceId: 2, rotation: -1 },
        },
        {
          id: 'n38',
          type: 'combineFields',
          label: 'green heights',
          folder: 'the frontier',
          comment:
            'Eroded terrain gated to the green side: one field whose high band is the unburnt ridges and whose middle bands are the living lowlands. Every green settlement and creature below is a band of it.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n9', b: 'n18' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n39',
          type: 'scatterPoints',
          label: 'watch outposts',
          folder: 'the frontier',
          comment:
            'Rare towers on the green ridges, looking east. There are none in the ashfall — the eastern watch is what the scorched wards used to be.',
          enabled: true,
          params: { density: 0.0006, maskAtLeast: 0.68, maskAtMost: 1 },
          inputs: { mask: 'n38' },
          display: { mode: 'pieces', pieceId: 1, rotation: 0 },
        },
        {
          id: 'n40',
          type: 'scatterPoints',
          label: 'outpost watch',
          folder: 'the frontier',
          comment: 'Sentries holding the same high band as their towers, walking back to their posts when you leave.',
          enabled: true,
          params: { density: 0.0012, maskAtLeast: 0.68, maskAtMost: 1 },
          inputs: { mask: 'n38' },
          display: { mode: 'creatures', creatureId: 3 },
        },
        {
          id: 'n41',
          type: 'scatterPoints',
          label: 'cottages',
          folder: 'the frontier',
          comment: 'Farmsteads across the mild green lowlands, and nowhere east of the stones — nobody rebuilds on ash.',
          enabled: true,
          params: { density: 0.0015, maskAtLeast: 0.55, maskAtMost: 0.64 },
          inputs: { mask: 'n38' },
          display: { mode: 'pieces', pieceId: 0, rotation: -1 },
        },
        {
          id: 'n42',
          type: 'scatterPoints',
          label: 'the greenwood',
          folder: 'who lives where',
          comment: 'The living forest of the west, on the same band its burnt twin occupies at the frontier.',
          enabled: true,
          params: { density: 0.07, maskAtLeast: 0.56, maskAtMost: 0.66 },
          inputs: { mask: 'n38' },
          display: { mode: 'markers', tileId: 3, glyph: '♠', color: '#2d6a34' },
        },
        {
          id: 'n43',
          type: 'scatterPoints',
          label: 'deer',
          folder: 'who lives where',
          comment:
            'Meadow herds whose band overlaps the warded lots — deer graze inside the overgrown hedge mazes, which is the closest thing the wards still have to a keeper.',
          enabled: true,
          params: { density: 0.006, maskAtLeast: 0.54, maskAtMost: 0.68 },
          inputs: { mask: 'n38' },
          display: { mode: 'creatures', creatureId: 0 },
        },
        {
          id: 'n44',
          type: 'scatterPoints',
          label: 'rabbits',
          folder: 'who lives where',
          comment: 'The low meadows near the coast, one band under the deer.',
          enabled: true,
          params: { density: 0.006, maskAtLeast: 0.52, maskAtMost: 0.6 },
          inputs: { mask: 'n38' },
          display: { mode: 'creatures', creatureId: 1 },
        },
        {
          id: 'n45',
          type: 'scatterPoints',
          label: 'wolves',
          folder: 'who lives where',
          comment: 'Hunting the greenwood band and a little above it — between the deer and the outposts.',
          enabled: true,
          params: { density: 0.0018, maskAtLeast: 0.6, maskAtMost: 0.72 },
          inputs: { mask: 'n38' },
          display: { mode: 'creatures', creatureId: 2 },
        },
        {
          id: 'n46',
          type: 'combineFields',
          label: 'fen strip',
          folder: 'who lives where',
          comment: 'Coast distance gated to the green side: its just-above-0.5 band is the marshy waterline itself.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n11', b: 'n18' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n47',
          type: 'scatterPoints',
          label: 'fen herons',
          folder: 'who lives where',
          comment: 'Stalking the first few tiles inland along the green coasts, quick to startle.',
          enabled: true,
          params: { density: 0.004, maskAtLeast: 0.52, maskAtMost: 0.58 },
          inputs: { mask: 'n46' },
          display: { mode: 'creatures', creatureId: 6 },
        },
        {
          id: 'n48',
          type: 'scatterPoints',
          label: 'ash hounds',
          folder: 'who lives where',
          comment: 'The deep east belongs to the hounds: fast, far-sighted, and the reason to keep moving out there.',
          enabled: true,
          params: { density: 0.002, maskAtLeast: 0.68, maskAtMost: 1 },
          inputs: { mask: 'n35' },
          display: { mode: 'creatures', creatureId: 4 },
        },
        {
          id: 'n49',
          type: 'scatterPoints',
          label: 'ember wisps',
          folder: 'who lives where',
          comment:
            'Spawned from the molten carve field, so they drift along the rivers of fire — phasing through lava and ward walls alike, the only gentle things left in the east.',
          enabled: true,
          params: { density: 0.02, maskAtLeast: 0.02, maskAtMost: 1 },
          inputs: { mask: 'n33' },
          display: { mode: 'creatures', creatureId: 5 },
        },
        {
          id: 'n50',
          type: 'combineFields',
          label: 'fallen wards',
          folder: 'who lives where',
          comment: 'Warded land east of the emberline — the scorched mazes.',
          enabled: true,
          params: { operation: 2, clamp: 1 },
          inputs: { a: 'n20', b: 'n15' },
          display: { mode: 'hidden' },
        },
        {
          id: 'n51',
          type: 'scatterPoints',
          label: 'ward sentries',
          folder: 'who lives where',
          comment:
            'The garrison of the fallen wards, still walking the scorched corridors. They guard their spawn corridor and return to it — the last order they were given.',
          enabled: true,
          params: { density: 0.004, maskAtLeast: 0.5, maskAtMost: 1 },
          inputs: { mask: 'n50' },
          display: { mode: 'creatures', creatureId: 3 },
        },
      ],
    },
  };
}

const EMBERLINE_SCRIPT = `const field = ctx.newField();
const greenEdgeX = -768;
const ashEdgeX = 768;
for (let y = 0; y < ctx.size; y++) {
  for (let x = 0; x < ctx.size; x++) {
    const eastwardness = (ctx.originX + x - greenEdgeX) / (ashEdgeX - greenEdgeX);
    field[y * ctx.size + x] = Math.max(0, Math.min(1, eastwardness));
  }
}
return field;`;

const WARD_LOTS_SCRIPT = `const field = ctx.newField();
const lotSpan = 192;
for (let y = 0; y < ctx.size; y++) {
  for (let x = 0; x < ctx.size; x++) {
    const lotX = Math.floor((ctx.originX + x) / lotSpan);
    const lotY = Math.floor((ctx.originY + y) / lotSpan);
    const warded = ctx.hash01(lotX, lotY, 'ward lot') < 0.28;
    field[y * ctx.size + x] = warded ? 1 : 0;
  }
}
return field;`;

const SCORCH_AND_BREACH_SCRIPT = `const maze = ctx.tilesInput('a');
const char = ctx.fieldInput('b');
const tiles = ctx.newTiles();
if (!maze || !char) return tiles;
const hedgeWall = 24;
const wardPath = 8;
const scorchedWall = 23;
const ashGround = 22;
for (let y = 0; y < ctx.size; y++) {
  for (let x = 0; x < ctx.size; x++) {
    const i = y * ctx.size + x;
    tiles[i] = -1;
    if (char[i] < 0.62) continue;
    const ruin = ctx.hash01(ctx.originX + x, ctx.originY + y, 'scorch');
    if (maze[i] === hedgeWall) tiles[i] = ruin < 0.3 ? ashGround : scorchedWall;
    if (maze[i] === wardPath) tiles[i] = ashGround;
  }
}
return tiles;`;
