import { defaultTileId } from '../../assets/tiles/defaultTiles';
import type { ExamplePipeline } from './examplePipeline';

const SEA_LEVEL = 0.5;

export function mountainsLakesAndRapids(): ExamplePipeline {
  return {
    name: 'mountains, lakes & rapids',
    description:
      'A world assembled around where its water goes. Plates raise the ranges, rain routed downhill carves the valleys and draws the rivers, every hollow the terrain closes fills to its spill level as a lake, and the reaches where a river is both deep and steep break white.',
    state: {
      seed: 3,
      nodes: [
        {
          id: 'plates',
          type: 'tectonicUplift',
          label: 'plates',
          folder: 'the ranges',
          comment:
            'Continents and ocean basins before any noise touches them. A land height of 0.6 against sea level 0.5 leaves a narrow margin, so the noise below is what decides which continental edges drown into bays.',
          enabled: true,
          params: { plateSize: 256, oceanFraction: 0.55, beltWidth: 64, rangeHeight: 0.34, landHeight: 0.6, basinDepth: 0.34 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpX',
          type: 'terrainNoise',
          label: 'warp x',
          folder: 'the ranges',
          comment: 'How far east or west to displace the plate field. Separate from the y axis so the displacement swirls rather than slides.',
          enabled: true,
          params: { scale: 0.004, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpY',
          type: 'terrainNoise',
          label: 'warp y',
          folder: 'the ranges',
          comment: 'The north-south half of the same displacement, at a slightly different scale so the two axes never line up into a diagonal grain.',
          enabled: true,
          params: { scale: 0.0045, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpedPlates',
          type: 'domainWarp',
          label: 'warped plates',
          folder: 'the ranges',
          comment: 'Plate boundaries are straight bisectors, which no real coast is. Displacing the field turns them into headlands, bays and offshore islands without changing a single elevation value.',
          enabled: true,
          params: { strength: 110 },
          inputs: { source: 'plates', offsetX: 'warpX', offsetY: 'warpY' },
          display: { mode: 'hidden' },
        },
        {
          id: 'beltMask',
          type: 'hypsometricCurve',
          label: 'belt mask',
          folder: 'the ranges',
          comment: 'A curve used as a switch: pivoted above continental crust but below the uplift belts, it reads near 1 inside a mountain belt and near 0 everywhere else. This is what keeps jagged noise on the ranges.',
          enabled: true,
          params: { seaLevel: 0.72, steepness: 25 },
          inputs: { source: 'warpedPlates' },
          display: { mode: 'hidden' },
        },
        {
          id: 'ridges',
          type: 'terrainNoise',
          label: 'ridges',
          folder: 'the ranges',
          comment: 'Ridged noise, each octave folded at its midline so crests are sharp and flanks are steep. Masked to the belts below, or it would ridge the whole world.',
          enabled: true,
          params: { scale: 0.01, style: 1, octaves: 7, lacunarity: 2.1, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'ranges',
          type: 'blendFields',
          label: 'ranges in the belts',
          folder: 'the ranges',
          comment: 'Mixes ridged noise into the plate uplift only where the belt mask allows. The weight is kept well under half deliberately: a blend leans toward whichever side it weights, so a heavy weight would replace the uplift with noise averaging near the middle and flatten the belt into a plateau. At this weight the ridges ride on top of the uplift instead.',
          enabled: true,
          params: { weight: 0.38 },
          inputs: { a: 'warpedPlates', b: 'ridges', mask: 'beltMask' },
          display: { mode: 'hidden' },
        },
        {
          id: 'hillNoise',
          type: 'terrainNoise',
          label: 'hill noise',
          folder: 'the hills',
          comment: 'The unremarkable relief between the ranges: rises, hollows, and the wobble that gives the coastline its small-scale shape. The hollows matter here — they are what later fills as lakes.',
          enabled: true,
          params: { scale: 0.018, style: 0, octaves: 5, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'hills',
          type: 'blendFields',
          label: 'rolling hills',
          folder: 'the hills',
          comment: 'A light unmasked pass over everything, kept low so it textures the terrain rather than competing with the plate structure.',
          enabled: true,
          params: { weight: 0.2 },
          inputs: { a: 'ranges', b: 'hillNoise' },
          display: { mode: 'hidden' },
        },
        {
          id: 'terrain',
          type: 'hypsometricCurve',
          label: 'basins & platform',
          folder: 'the hills',
          comment: 'Earth has two typical elevations with a steep slope between them and almost nothing sitting exactly at sea level. This pushes the blended field into that shape, which is what stops the map being fringed with shallows everywhere.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, steepness: 9 },
          inputs: { source: 'hills' },
          display: { mode: 'hidden' },
        },
        {
          id: 'flow',
          type: 'flowAccumulation',
          label: 'drainage',
          folder: 'the water',
          comment:
            'One unit of rain on every cell, routed downhill after the pits are flooded shut. Below the channel threshold the water spreads across several neighbours the way runoff really does; above it the watercourse commits to one path, which is what keeps trunks from fraying into speckle.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, catchmentScale: 2200, convergence: 4, channelizeAbove: 20, fillPits: 1, windowRadius: 48 },
          inputs: { elevation: 'terrain' },
          display: { mode: 'hidden' },
        },
        {
          id: 'eroded',
          type: 'carveValleys',
          label: 'eroded terrain',
          folder: 'the water',
          comment: 'Rivers cut in proportion to what they carry, so channels sit in valleys and the ground between them reads as ridges because it is what did not get cut away.',
          enabled: true,
          params: { depth: 0.14, minFlow: 0.62, valleyWidth: 7 },
          inputs: { elevation: 'terrain', flow: 'flow' },
          display: { mode: 'hidden' },
        },
        {
          id: 'seaFloor',
          type: 'constantField',
          label: 'sea level',
          folder: 'the hollows',
          comment: 'One flat value at sea level. Used twice: as the floor the ocean surface is lifted to, and as the level the basins below are pulled toward.',
          enabled: true,
          params: { value: SEA_LEVEL },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'basinNoise',
          type: 'terrainNoise',
          label: 'basin noise',
          folder: 'the hollows',
          comment: 'The frequency here is the whole trick. A scooped hollow only holds water if its sides fall faster than the hillside it sits on rises, so a broad gentle dip just tilts downhill and drains. Patches a few dozen tiles across are compact enough to win that race.',
          enabled: true,
          params: { scale: 0.03, style: 0, octaves: 3, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'basinMask',
          type: 'hypsometricCurve',
          label: 'basin mask',
          folder: 'the hollows',
          comment: 'The same curve-as-a-switch trick the mountain belts use, pivoted high so only the top of the noise survives. That leaves scattered closed islands of mask rather than a connected web, which matters: a hollow open along one side is a valley, and only a hollow closed on every side holds water.',
          enabled: true,
          params: { seaLevel: 0.62, steepness: 40 },
          inputs: { source: 'basinNoise' },
          display: { mode: 'hidden' },
        },
        {
          id: 'dimpled',
          type: 'blendFields',
          label: 'scooped basins',
          folder: 'the hollows',
          comment:
            'Pulls the ground toward sea level inside those islands, scooping shallow closed hollows into the landscape. Nothing else here can make one: the hypsometric curve is monotonic so it cannot invent a pit, and fill depressions can only flood hollows that already exist. It runs after the valleys are cut on purpose — scooped first, the rivers simply carve an outlet through every basin and drain it, which is exactly what happened before this node sat here.',
          enabled: true,
          params: { weight: 0.8 },
          inputs: { a: 'eroded', b: 'seaFloor', mask: 'basinMask' },
          display: { mode: 'hidden' },
        },
        {
          id: 'lakeSurface',
          type: 'fillDepressions',
          label: 'lake surface',
          folder: 'the water',
          comment:
            'Floods every closed hollow up to the point it would spill from. This is also the elevation the world is built on, and that is deliberate: inside a basin the flooded surface is flat, so the lake sits at one level instead of draping over its own bed.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, maxFill: 0.18, windowRadius: 64 },
          inputs: { elevation: 'dimpled' },
          display: { mode: 'hidden' },
        },
        {
          id: 'surface',
          type: 'combineFields',
          label: 'water surface',
          folder: 'the water',
          comment:
            'The elevation the world is actually built on, and the reason the sea is flat. Filling depressions leaves everything at or below sea level untouched, because those cells already drain to the ocean — so the raw flooded field still slopes all the way down the sea bed, and painting ocean tiles onto it would render the sea as a ramp descending into a hole. Taking the higher of the flooded surface and sea level puts every ocean cell at one height while leaving all the land, and every inland lake perched above sea level, exactly as the flooding left them.',
          enabled: true,
          params: { operation: 4, clamp: 1 },
          inputs: { a: 'lakeSurface', b: 'seaFloor' },
          display: { mode: 'elevation', heightScale: 55 },
        },
        {
          id: 'steepness',
          type: 'slopeField',
          label: 'steepness',
          folder: 'the surface',
          comment: 'Bare rock and broken water are both questions about grade rather than height. Radius 3 measures the slope of a mountainside instead of the roughness of single cells.',
          enabled: true,
          params: { radius: 3, gain: 8 },
          inputs: { source: 'dimpled' },
          display: { mode: 'hidden' },
        },
        {
          id: 'coast',
          type: 'coastDistance',
          label: 'coast distance',
          folder: 'the surface',
          comment: 'Measured from the eroded terrain so beaches follow the shore rather than the local gradient, and river valleys do not count as coastline.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, range: 24 },
          inputs: { elevation: 'dimpled' },
          display: { mode: 'hidden' },
        },
        {
          id: 'land',
          type: 'biomeBands',
          label: 'land & ocean',
          folder: 'the surface',
          comment: 'The whole tile mapping on one card: ocean, shelf, beach, meadow, the bare rock that only clings to steep ground, and snow on the summits.',
          enabled: true,
          params: {
            seaLevel: SEA_LEVEL,
            deepDrop: 0.07,
            shoreBand: 0.05,
            rockAbove: 0.3,
            snowLine: 0.88,
            regionAtLeast: 0.5,
            deepTile: defaultTileId('sea water'),
            waterTile: defaultTileId('shallow water'),
            shoreTile: defaultTileId('shore sand'),
            groundTile: defaultTileId('meadow grass'),
            rockTile: defaultTileId('granite outcrop'),
            snowTile: defaultTileId('snowfield'),
          },
          inputs: { elevation: 'dimpled', steepness: 'steepness', shoreDistance: 'coast', region: null },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'rivers',
          type: 'riverFromFlow',
          label: 'rivers',
          folder: 'the water',
          comment: 'Painted under the lakes, so a river running into a basin becomes the lake rather than a channel drawn across it. Every cell above the flow threshold is water, so courses branch upstream, merge downstream, and widen toward the mouth.',
          enabled: true,
          params: { minFlow: 0.42, maxWidth: 8, seaLevel: SEA_LEVEL, riverTile: defaultTileId('river water') },
          inputs: { flow: 'flow', elevation: 'dimpled' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'lakes',
          type: 'lakeFromFill',
          label: 'lakes',
          folder: 'the water',
          comment: 'Painted after the rivers that feed them. The difference between the flooded surface and the ground under it. Shallow margins shelve into deep water, so a lake has an edge rather than a wall.',
          enabled: true,
          params: {
            seaLevel: SEA_LEVEL,
            minDepth: 0.004,
            shallowDepth: 0.016,
            lakeTile: defaultTileId('lake water'),
            shallowTile: defaultTileId('shallow water'),
          },
          inputs: { ground: 'dimpled', flooded: 'lakeSurface' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'rapids',
          type: 'rapidsFromFlow',
          label: 'rapids',
          folder: 'the water',
          comment: 'Last layer, so broken water sits on top of the river it belongs to. Its flow threshold is at or above the river threshold, which keeps rapids on watercourses instead of on dry steep ground.',
          enabled: true,
          params: { minFlow: 0.6, minSteepness: 0.05, seaLevel: SEA_LEVEL, rapidsTile: defaultTileId('whitewater') },
          inputs: { flow: 'flow', steepness: 'steepness', elevation: 'dimpled' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'conifers',
          type: 'scatterPoints',
          label: 'conifers',
          folder: 'the cover',
          comment:
            'Billboards are the only things in this view with their own colour — ground stands a block deep, which walls off the void under a slope but leaves a hillside of grass one uniform green whatever its height. Trees are what stops the land reading as a stack of painted sheets. Pines take the upper band, below the snow line.',
          enabled: true,
          params: { density: 0.05, maskAtLeast: 0.63, maskAtMost: 0.78 },
          inputs: { mask: 'dimpled' },
          display: { mode: 'markers', tileId: 13, glyph: '♣', color: '#37603f' },
        },
        {
          id: 'broadleaf',
          type: 'scatterPoints',
          label: 'broadleaf wood',
          folder: 'the cover',
          comment: 'Oaks on the lower slopes and valley floors, where it is warmer and the ground is worked by rivers rather than frost.',
          enabled: true,
          params: { density: 0.055, maskAtLeast: 0.53, maskAtMost: 0.65 },
          inputs: { mask: 'dimpled' },
          display: { mode: 'markers', tileId: 3, glyph: '♠', color: '#41663c' },
        },
        {
          id: 'scrub',
          type: 'scatterPoints',
          label: 'scrub',
          folder: 'the cover',
          comment: 'Hazel filling the gaps between the two woods, so the treeline is a gradient rather than a hard edge.',
          enabled: true,
          params: { density: 0.03, maskAtLeast: 0.6, maskAtMost: 0.72 },
          inputs: { mask: 'dimpled' },
          display: { mode: 'markers', tileId: 14, glyph: '%', color: '#4e7443' },
        },
        {
          id: 'boulders',
          type: 'scatterPoints',
          label: 'boulders',
          folder: 'the cover',
          comment: 'Rock scattered on the steep ground above the treeline, drawn as boulders because the tile it is styled from has the rock role.',
          enabled: true,
          params: { density: 0.02, maskAtLeast: 0.78, maskAtMost: 1 },
          inputs: { mask: 'dimpled' },
          display: { mode: 'markers', tileId: 4, glyph: '#', color: '#8b8c87' },
        },
      ],
    },
  };
}
