import { defaultTileId } from '../../assets/tiles/defaultTiles';
import type { ExamplePipeline } from './examplePipeline';

const SEA_LEVEL = 0.5;

export function mountainsLakesAndRapids(): ExamplePipeline {
  return {
    name: 'mountains, lakes & rapids',
    description:
      'A world assembled around where its water goes. Plates raise the ranges, rain routed downhill carves the valleys and draws the rivers, every hollow the terrain closes fills to its spill level as a lake, and the reaches where a river is both deep and steep break white.',
    state: {
      seed: 3,
      nodes: [
        {
          id: 'plates',
          type: 'tectonicUplift',
          label: 'plates',
          folder: 'the ranges',
          comment:
            'Continents and ocean basins before any noise touches them. A land height of 0.6 against sea level 0.5 leaves a narrow margin, so the noise below is what decides which continental edges drown into bays.',
          enabled: true,
          params: { plateSize: 256, oceanFraction: 0.55, beltWidth: 64, rangeHeight: 0.34, landHeight: 0.6, basinDepth: 0.34 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpX',
          type: 'terrainNoise',
          label: 'warp x',
          folder: 'the ranges',
          comment: 'How far east or west to displace the plate field. Separate from the y axis so the displacement swirls rather than slides.',
          enabled: true,
          params: { scale: 0.004, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpY',
          type: 'terrainNoise',
          label: 'warp y',
          folder: 'the ranges',
          comment: 'The north-south half of the same displacement, at a slightly different scale so the two axes never line up into a diagonal grain.',
          enabled: true,
          params: { scale: 0.0045, style: 0, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'warpedPlates',
          type: 'domainWarp',
          label: 'warped plates',
          folder: 'the ranges',
          comment: 'Plate boundaries are straight bisectors, which no real coast is. Displacing the field turns them into headlands, bays and offshore islands without changing a single elevation value.',
          enabled: true,
          params: { strength: 110 },
          inputs: { source: 'plates', offsetX: 'warpX', offsetY: 'warpY' },
          display: { mode: 'hidden' },
        },
        {
          id: 'beltMask',
          type: 'hypsometricCurve',
          label: 'belt mask',
          folder: 'the ranges',
          comment: 'A curve used as a switch: pivoted above continental crust but below the uplift belts, it reads near 1 inside a mountain belt and near 0 everywhere else. This is what keeps jagged noise on the ranges.',
          enabled: true,
          params: { seaLevel: 0.72, steepness: 25 },
          inputs: { source: 'warpedPlates' },
          display: { mode: 'hidden' },
        },
        {
          id: 'ridges',
          type: 'terrainNoise',
          label: 'ridges',
          folder: 'the ranges',
          comment: 'Ridged noise, each octave folded at its midline so crests are sharp and flanks are steep. Masked to the belts below, or it would ridge the whole world.',
          enabled: true,
          params: { scale: 0.01, style: 1, octaves: 7, lacunarity: 2.1, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'ranges',
          type: 'blendFields',
          label: 'ranges in the belts',
          folder: 'the ranges',
          comment: 'Mixes ridged noise into the plate uplift only where the belt mask allows. The weight is kept well under half deliberately: a blend leans toward whichever side it weights, so a heavy weight would replace the uplift with noise averaging near the middle and flatten the belt into a plateau. At this weight the ridges ride on top of the uplift instead.',
          enabled: true,
          params: { weight: 0.38 },
          inputs: { a: 'warpedPlates', b: 'ridges', mask: 'beltMask' },
          display: { mode: 'hidden' },
        },
        {
          id: 'hillNoise',
          type: 'terrainNoise',
          label: 'hill noise',
          folder: 'the hills',
          comment: 'The unremarkable relief between the ranges: rises, hollows, and the wobble that gives the coastline its small-scale shape. The hollows matter here — they are what later fills as lakes.',
          enabled: true,
          params: { scale: 0.018, style: 0, octaves: 5, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'hills',
          type: 'blendFields',
          label: 'rolling hills',
          folder: 'the hills',
          comment: 'A light unmasked pass over everything, kept low so it textures the terrain rather than competing with the plate structure.',
          enabled: true,
          params: { weight: 0.2 },
          inputs: { a: 'ranges', b: 'hillNoise' },
          display: { mode: 'hidden' },
        },
        {
          id: 'terrain',
          type: 'hypsometricCurve',
          label: 'basins & platform',
          folder: 'the hills',
          comment: 'Earth has two typical elevations with a steep slope between them and almost nothing sitting exactly at sea level. This pushes the blended field into that shape, which is what stops the map being fringed with shallows everywhere.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, steepness: 9 },
          inputs: { source: 'hills' },
          display: { mode: 'hidden' },
        },
        {
          id: 'flow',
          type: 'flowAccumulation',
          label: 'drainage',
          folder: 'the water',
          comment:
            'One unit of rain on every cell, routed downhill after the pits are flooded shut. Below the channel threshold the water spreads across several neighbours the way runoff really does; above it the watercourse commits to one path, which is what keeps trunks from fraying into speckle.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, catchmentScale: 2200, convergence: 4, channelizeAbove: 20, fillPits: 1, windowRadius: 48 },
          inputs: { elevation: 'terrain' },
          display: { mode: 'hidden' },
        },
        {
          id: 'eroded',
          type: 'carveValleys',
          label: 'eroded terrain',
          folder: 'the water',
          comment: 'Rivers cut in proportion to what they carry, so channels sit in valleys and the ground between them reads as ridges because it is what did not get cut away.',
          enabled: true,
          params: { depth: 0.09, minFlow: 0.35, valleyWidth: 7 },
          inputs: { elevation: 'terrain', flow: 'flow' },
          display: { mode: 'hidden' },
        },
        {
          id: 'lakeSurface',
          type: 'fillDepressions',
          label: 'lake surface',
          folder: 'the water',
          comment:
            'Floods every closed hollow up to the point it would spill from. This is also the elevation the world is built on, and that is deliberate: inside a basin the flooded surface is flat, so the lake sits at one level instead of draping over its own bed.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, maxFill: 0.18, windowRadius: 64 },
          inputs: { elevation: 'eroded' },
          display: { mode: 'elevation', heightScale: 26 },
        },
        {
          id: 'steepness',
          type: 'slopeField',
          label: 'steepness',
          folder: 'the surface',
          comment: 'Bare rock and broken water are both questions about grade rather than height. Radius 3 measures the slope of a mountainside instead of the roughness of single cells.',
          enabled: true,
          params: { radius: 3, gain: 14 },
          inputs: { source: 'eroded' },
          display: { mode: 'hidden' },
        },
        {
          id: 'coast',
          type: 'coastDistance',
          label: 'coast distance',
          folder: 'the surface',
          comment: 'Measured from the eroded terrain so beaches follow the shore rather than the local gradient, and river valleys do not count as coastline.',
          enabled: true,
          params: { seaLevel: SEA_LEVEL, range: 24 },
          inputs: { elevation: 'eroded' },
          display: { mode: 'hidden' },
        },
        {
          id: 'land',
          type: 'biomeBands',
          label: 'land & ocean',
          folder: 'the surface',
          comment: 'The whole tile mapping on one card: ocean, shelf, beach, meadow, the bare rock that only clings to steep ground, and snow on the summits.',
          enabled: true,
          params: {
            seaLevel: SEA_LEVEL,
            deepDrop: 0.07,
            shoreBand: 0.05,
            rockAbove: 0.42,
            snowLine: 0.88,
            regionAtLeast: 0.5,
            deepTile: defaultTileId('sea water'),
            waterTile: defaultTileId('shallow water'),
            shoreTile: defaultTileId('shore sand'),
            groundTile: defaultTileId('meadow grass'),
            rockTile: defaultTileId('granite outcrop'),
            snowTile: defaultTileId('snowfield'),
          },
          inputs: { elevation: 'eroded', steepness: 'steepness', shoreDistance: 'coast', region: null },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'rivers',
          type: 'riverFromFlow',
          label: 'rivers',
          folder: 'the water',
          comment: 'Painted under the lakes, so a river running into a basin becomes the lake rather than a channel drawn across it. Every cell above the flow threshold is water, so courses branch upstream, merge downstream, and widen toward the mouth.',
          enabled: true,
          params: { minFlow: 0.5, maxWidth: 5, seaLevel: SEA_LEVEL, riverTile: defaultTileId('river water') },
          inputs: { flow: 'flow', elevation: 'eroded' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'lakes',
          type: 'lakeFromFill',
          label: 'lakes',
          folder: 'the water',
          comment: 'Painted after the rivers that feed them. The difference between the flooded surface and the ground under it. Shallow margins shelve into deep water, so a lake has an edge rather than a wall.',
          enabled: true,
          params: {
            seaLevel: SEA_LEVEL,
            minDepth: 0.004,
            shallowDepth: 0.016,
            lakeTile: defaultTileId('lake water'),
            shallowTile: defaultTileId('shallow water'),
          },
          inputs: { ground: 'eroded', flooded: 'lakeSurface' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'rapids',
          type: 'rapidsFromFlow',
          label: 'rapids',
          folder: 'the water',
          comment: 'Last layer, so broken water sits on top of the river it belongs to. Its flow threshold is at or above the river threshold, which keeps rapids on watercourses instead of on dry steep ground.',
          enabled: true,
          params: { minFlow: 0.5, minSteepness: 0.28, seaLevel: SEA_LEVEL, rapidsTile: defaultTileId('whitewater') },
          inputs: { flow: 'flow', steepness: 'steepness', elevation: 'eroded' },
          display: { mode: 'tileLayer' },
        },
      ],
    },
  };
}
