import { STONEWOLD_CULTURE_ID, THATCHMERE_CULTURE_ID } from '../../assets/cultures/defaultCultures';
import { defaultTileId } from '../../assets/tiles/defaultTiles';
import type { ExamplePipeline } from './examplePipeline';

export function thatchmereVale(): ExamplePipeline {
  return {
    name: 'thatchmere vale',
    description:
      'A pastoral valley with the whole asset library standing in it: a drowned coast and rolling pasture, becks running down to the sea, thatch-and-wattle villages of thatchmere along the lowland lanes, and granite-and-slate stonewold hamlets up on the shoulders of the fells.',
    state: {
      seed: 8123,
      nodes: [
        {
          id: 'n1',
          type: 'terrainNoise',
          label: 'vale relief',
          folder: 'the vale',
          comment:
            'The one field the whole vale answers to. A gentle scale and five octaves give long pasture slopes rather than islands, and every layer below — coast, woods, villages, becks — reads this node so nothing can disagree about where the ground is.',
          enabled: true,
          params: { scale: 0.006, style: 0, octaves: 5, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'elevation', heightScale: 4 },
        },
        {
          id: 'n2',
          type: 'thresholdTiles',
          label: 'sea & strand',
          folder: 'the vale',
          comment:
            'The base coat, so every cell starts painted: sea water below 0.42 and shore sand above. Everything after this only overrides parts of it.',
          enabled: true,
          params: {
            threshold: 0.42,
            belowTile: defaultTileId('sea water'),
            aboveTile: defaultTileId('shore sand'),
          },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n3',
          type: 'thresholdTiles',
          label: 'shallows',
          folder: 'the vale',
          comment:
            'A thin band of shallow water above the deep, painted below 0.40 and left empty above, so the coast reads as a beach shelving into the sea instead of a wall of blue.',
          enabled: true,
          params: { threshold: 0.4, belowTile: -1, aboveTile: defaultTileId('shallow water') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n4',
          type: 'thresholdTiles',
          label: 'marsh',
          folder: 'the vale',
          comment:
            'A wet band immediately above the tideline: everything over 0.43 is fen until the pasture layer below overrides it at 0.45, which leaves exactly the two-tile margin where the becks spill out.',
          enabled: true,
          params: { threshold: 0.43, belowTile: -1, aboveTile: defaultTileId('marsh') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n5',
          type: 'thresholdTiles',
          label: 'pasture',
          folder: 'the vale',
          comment:
            'Grass only above 0.45, which leaves a sand strand two or three tiles wide along the whole shore for the villages to sit back from.',
          enabled: true,
          params: { threshold: 0.45, belowTile: -1, aboveTile: defaultTileId('meadow grass') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n6',
          type: 'thresholdTiles',
          label: 'upper pasture',
          folder: 'the vale',
          comment:
            'A second, paler grass above 0.56. Two grasses rather than one is what stops the middle of the map reading as a single flat green.',
          enabled: true,
          params: { threshold: 0.56, belowTile: -1, aboveTile: defaultTileId('pasture grass') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n7',
          type: 'thresholdTiles',
          label: 'fell scree',
          folder: 'the vale',
          comment:
            'Loose stone above 0.70 where the pasture gives out, so the fells have a skirt of scree before the bare rock starts.',
          enabled: true,
          params: { threshold: 0.7, belowTile: -1, aboveTile: defaultTileId('scree') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n8',
          type: 'thresholdTiles',
          label: 'fell rock',
          folder: 'the vale',
          comment:
            'Granite outcrop above 0.76 — the band the stonewold hamlets are masked to sit just below, so the hamlets read as hill settlements under the crags.',
          enabled: true,
          params: { threshold: 0.76, belowTile: -1, aboveTile: defaultTileId('granite outcrop') },
          inputs: { source: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n9',
          type: 'riverTiles',
          label: 'becks',
          folder: 'water',
          comment:
            'Springs on ground above 0.62 traced downhill to the same 0.42 sea level the coast uses, so every beck ends in a mouth on the strand rather than stopping in a field. A little meander keeps them from looking surveyed.',
          enabled: true,
          params: {
            sourceDensity: 0.0025,
            minSourceHeight: 0.62,
            seaLevel: 0.42,
            maxLength: 120,
            meander: 0.05,
            riverTile: defaultTileId('river water'),
          },
          inputs: { elevation: 'n1' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n10',
          type: 'villageCenters',
          label: 'vale villages',
          folder: 'thatchmere villages',
          comment:
            'Villages answer to the land: only the gentle inhabited band from 0.50 to 0.62 can hold one, which is clear of the marsh and well below the scree. Spacing 160 puts roughly one village every two and a half chunks of walking, so you cross fields between them instead of tripping over the next roof.',
          enabled: true,
          params: { maskAtLeast: 0.5, maskAtMost: 0.62, spacing: 160 },
          inputs: { mask: 'n1' },
          display: { mode: 'markers', tileId: -1, glyph: '⌂', color: '#e0c48a' },
        },
        {
          id: 'n11',
          type: 'villageStreets',
          label: 'vale lanes',
          folder: 'thatchmere villages',
          comment:
            'The same centers and the same layout knobs as the plots below, which is what makes the paving line up with the houses. Cobbles for the street, flagstones for the square where the two lanes cross.',
          enabled: true,
          params: {
            radius: 72,
            plotCells: 16,
            streetWidth: 3,
            streetTile: defaultTileId('cobbled street'),
            plazaTile: defaultTileId('flagstone plaza'),
          },
          inputs: { centers: 'n10' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n12',
          type: 'villagePlots',
          label: 'vale houses',
          folder: 'thatchmere villages',
          comment:
            'One tagged plot per building, bound to thatchmere so every point grows into a wattle-walled, thatch-roofed house assembled from the piece library. Plots are 16 tiles square because that is the smallest plot a town hall fits in; below that the plaza slot quietly falls back to a cottage. The rings do the zoning: the town hall on the plaza, inns around it, the workshop ring of smithies behind them, and houses on everything further out.',
          enabled: true,
          params: {
            radius: 72,
            plotCells: 16,
            streetWidth: 3,
            cottageWeight: 5,
            dwellingWeight: 3,
            smithyWeight: 2,
            innWeight: 1,
            townHallWeight: 1,
          },
          inputs: { centers: 'n10' },
          display: { mode: 'structures', cultureId: THATCHMERE_CULTURE_ID },
        },
        {
          id: 'n13',
          type: 'villageCenters',
          label: 'fell hamlets',
          folder: 'stonewold hamlets',
          comment:
            'A second, tighter band from 0.63 to 0.71 — the shoulder of the fell between the pasture and the scree. Because the band never overlaps the vale band, the two cultures can never found a village on the same ground.',
          enabled: true,
          params: { maskAtLeast: 0.63, maskAtMost: 0.71, spacing: 112 },
          inputs: { mask: 'n1' },
          display: { mode: 'markers', tileId: -1, glyph: '⌂', color: '#a8b0b6' },
        },
        {
          id: 'n14',
          type: 'villageStreets',
          label: 'hamlet lanes',
          folder: 'stonewold hamlets',
          comment:
            'A quarter of the vale radius and 10-tile plots, so a hamlet is one short street rather than a town. Same cobble and flagstone paving, because the quarry that dressed the walls also paved the lane.',
          enabled: true,
          params: {
            radius: 26,
            plotCells: 10,
            streetWidth: 3,
            streetTile: defaultTileId('cobbled street'),
            plazaTile: defaultTileId('flagstone plaza'),
          },
          inputs: { centers: 'n13' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'n15',
          type: 'villagePlots',
          label: 'hamlet houses',
          folder: 'stonewold hamlets',
          comment:
            'Bound to stonewold: granite walls, slate hips and the taller stories that the extra story layer buys. Every civic weight is zero, so a hamlet comes out as nothing but cottages and dwellings, which is the whole difference between a hamlet and the town down in the vale.',
          enabled: true,
          params: {
            radius: 26,
            plotCells: 10,
            streetWidth: 3,
            cottageWeight: 5,
            dwellingWeight: 2,
            smithyWeight: 0,
            innWeight: 0,
            townHallWeight: 0,
          },
          inputs: { centers: 'n13' },
          display: { mode: 'structures', cultureId: STONEWOLD_CULTURE_ID },
        },
        {
          id: 'n16',
          type: 'scatterPoints',
          label: 'oak woods',
          folder: 'woods & wildlife',
          comment:
            'Oaks on the lower slopes only, in the same band the villages take, so the woods and the fields interleave and every village has timber within walking distance.',
          enabled: true,
          params: { density: 0.05, maskAtLeast: 0.5, maskAtMost: 0.63 },
          inputs: { mask: 'n1' },
          display: { mode: 'markers', tileId: defaultTileId('oak tree'), glyph: '♠', color: '#41663c' },
        },
        {
          id: 'n17',
          type: 'scatterPoints',
          label: 'pine ridges',
          folder: 'woods & wildlife',
          comment:
            'Pines take over above the oaks, from 0.64 to the scree line, which is how a real treeline reads: the species changes before the trees stop.',
          enabled: true,
          params: { density: 0.04, maskAtLeast: 0.64, maskAtMost: 0.72 },
          inputs: { mask: 'n1' },
          display: { mode: 'markers', tileId: defaultTileId('pine tree'), glyph: '♣', color: '#37603f' },
        },
        {
          id: 'n18',
          type: 'scatterPoints',
          label: 'meadow flowers',
          folder: 'woods & wildlife',
          comment:
            'A thin scatter of flowers across the damp lower pasture. Cheap and unstructured on purpose: its only job is to break up the green where the eye rests longest.',
          enabled: true,
          params: { density: 0.03, maskAtLeast: 0.46, maskAtMost: 0.55 },
          inputs: { mask: 'n1' },
          display: {
            mode: 'markers',
            tileId: defaultTileId('meadow flowers'),
            glyph: '❀',
            color: '#8aa165',
          },
        },
        {
          id: 'n19',
          type: 'scatterPoints',
          label: 'deer',
          folder: 'woods & wildlife',
          comment:
            'Spawn cells rather than positions: each point near the player becomes one deer browsing the wood margin between the oaks and the fields.',
          enabled: true,
          params: { density: 0.008, maskAtLeast: 0.5, maskAtMost: 0.66 },
          inputs: { mask: 'n1' },
          display: { mode: 'creatures', creatureId: 0 },
        },
        {
          id: 'n20',
          type: 'scatterPoints',
          label: 'fen herons',
          folder: 'woods & wildlife',
          comment:
            'Masked to the wet band just above the tideline, so herons are found standing in the marsh the way they should be and never up on the fell.',
          enabled: true,
          params: { density: 0.004, maskAtLeast: 0.43, maskAtMost: 0.47 },
          inputs: { mask: 'n1' },
          display: { mode: 'creatures', creatureId: 6 },
        },
      ],
    },
  };
}
