import { defaultTileId } from '@/features/asset-library/tiles/defaultTiles';
import { CARVER_DFS } from '../nodes/maze/mazeCarvers';
import { COMBINE_ADD, COMBINE_MULTIPLY, COMBINE_SUBTRACT } from '../nodes/examples/combineFields';
import { NOISE_STYLE_FBM } from '../noise/terrainOctaves';
import type { ExamplePipeline } from './examplePipeline';

export const GORGE_RADIUS = 360;
export const GORGE_HEIGHT_SCALE = 12;
export const GORGE_FLOOR = 0.09;
export const CREVASSE_DEPTH = 0.08;
export const WALL_HEIGHT = 0.3;

export function sunkenLabyrinth(): ExamplePipeline {
  return {
    name: 'sunken labyrinth',
    description:
      'You wake in a bare clearing at the bottom of a great open-air gorge, ten ledges below the daylight meadows on its rim, ringed by a labyrinth walled with sheer rock. Uphill is always out: the ground climbs toward the rim in full-level shelves too tall to walk up, so follow the winding ramps where they run and jump (Space) the ledges where they do not. Crevasses wind across the corridors exactly one jump wide — leap them, or drop in and jump back out — and the labyrinth walls sink with the land as you rise, from towering rock crowned in granite, to head-height masonry, to hoppable ridges, until the last of them dissolves into the flowered surface.',
    state: {
      seed: 7414,
      daylight: 1,
      nodes: [
        {
          id: 'basin',
          type: 'basinField',
          label: 'the gorge',
          folder: 'the gorge',
          comment:
            'The whole idea of this world in one field: a bowl sunk around the spawn, floor 0.09 so the deepest crevasse still bottoms out above zero, rising to the surface at a radius of 360. Every other node reads this — the terraces climb it, the walls fade against it, the rim oaks grow where it tops out.',
          enabled: true,
          params: { centerX: 0, centerY: 0, radius: GORGE_RADIUS, floor: GORGE_FLOOR },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'grain',
          type: 'terrainNoise',
          label: 'rock grain',
          folder: 'the gorge',
          comment:
            'Medium-scale noise folded lightly over the bowl so the shelves waver and break instead of running as perfect rings. It is what makes two stretches of the same ledge different heights, so where a riser is jumpable is a local discovery rather than a rule.',
          enabled: true,
          params: { scale: 0.05, style: NOISE_STYLE_FBM, octaves: 4, lacunarity: 2, gain: 0.5 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'shaped',
          type: 'blendFields',
          label: 'grained bowl',
          folder: 'the gorge',
          comment:
            'The bowl with 12% noise mixed in — enough to roughen the contours, little enough that downhill still reliably points at the center and uphill at the rim.',
          enabled: true,
          params: { weight: 0.12 },
          inputs: { a: 'basin', b: 'grain' },
          display: { mode: 'hidden' },
        },
        {
          id: 'ramps',
          type: 'noiseField',
          label: 'where ramps run',
          folder: 'the gorge',
          comment:
            'A coarse noise the terrace node reads as its passes: where this runs high the slope stays smooth and walkable, everywhere else it snaps to shelves. Roughly a third of the gorge is ramp, so a patient walker can climb without ever jumping — but rarely in a straight line.',
          enabled: true,
          params: { scale: 0.035, octaves: 3 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'shelves',
          type: 'terraceField',
          label: 'the twelve shelves',
          folder: 'the gorge',
          comment:
            'The climb, cut into twelve flat shelves. With the height scale at 12 each riser is exactly one elevation level: too tall to walk up, exactly tall enough to jump up. This node is also what every ground-paint band reads, so the country changes color shelf by shelf as you rise.',
          enabled: true,
          params: { levels: 12, passesAbove: 0.63 },
          inputs: { source: 'shaped', passes: 'ramps' },
          display: { mode: 'hidden' },
        },
        {
          id: 'crackNoise',
          type: 'noiseField',
          label: 'crack pattern',
          folder: 'the crevasses',
          comment:
            'The slow noise whose middle contour becomes the crevasses. Its scale sets how often a corridor is cut: lower and the cracks become rare continental rifts, higher and every passage is stitched with them.',
          enabled: true,
          params: { scale: 0.02, octaves: 3 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'cracks',
          type: 'contourLine',
          label: 'crevasse lines',
          folder: 'the crevasses',
          comment:
            'The cells sitting one tile below the crack pattern’s midline — thin closed loops that wander across shelves, ramps and corridors alike. One tile wide is the whole design: a jump clears exactly one ignored tile, so these are crossable by leaping and by nothing else.',
          enabled: true,
          params: { level: 0.5, width: 1 },
          inputs: { source: 'crackNoise' },
          display: { mode: 'hidden' },
        },
        {
          id: 'crackDepth',
          type: 'constantField',
          label: 'one level deep',
          folder: 'the crevasses',
          comment:
            'How far a crevasse drops, in field units: 0.08 of a 12-level height scale is one navigation level. That exact depth is a promise — you can always jump back out of a crevasse you fell into, and never simply walk out.',
          enabled: true,
          params: { value: CREVASSE_DEPTH },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'cut',
          type: 'combineFields',
          label: 'the cut',
          folder: 'the crevasses',
          comment:
            'The crevasse lines scaled to their depth, ready to subtract from the ground. Kept separate so the crack-floor paint can read the raw lines while the elevation reads this.',
          enabled: true,
          params: { operation: COMBINE_MULTIPLY, clamp: 1 },
          inputs: { a: 'cracks', b: 'crackDepth' },
          display: { mode: 'hidden' },
        },
        {
          id: 'walls',
          type: 'mazeWallField',
          label: 'the labyrinth',
          folder: 'the labyrinth',
          comment:
            'The maze itself, as a field of wall cells. Corridors three tiles wide; walls two tiles thick so no jump clears one; each maze spans four chunks and opens to its neighbors through two doors per edge. A quarter of dead ends are braided into loops so a crevasse across one route is an inconvenience, not a wall.',
          enabled: true,
          params: {
            corridor: 3,
            wall: 2,
            mazeChunks: 4,
            carver: CARVER_DFS,
            braid: 0.25,
            doorsPerEdge: 2,
            rooms: 0.1,
            roomCells: 3,
          },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'one',
          type: 'constantField',
          label: 'one',
          folder: 'the labyrinth',
          comment: 'A flat 1, so the node below can turn the bowl inside out by subtracting it.',
          enabled: true,
          params: { value: 1 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'depthLeft',
          type: 'combineFields',
          label: 'depth still below you',
          folder: 'the labyrinth',
          comment:
            'One minus the bowl: full at the center, zero at the rim. The measure of how deep in the gorge a cell still is, which is what decides how much labyrinth still stands over it.',
          enabled: true,
          params: { operation: COMBINE_SUBTRACT, clamp: 1 },
          inputs: { a: 'one', b: 'basin' },
          display: { mode: 'hidden' },
        },
        {
          id: 'wallZones',
          type: 'terraceField',
          label: 'three wall heights',
          folder: 'the labyrinth',
          comment:
            'The remaining depth snapped to three steps, so the walls stand at three discrete heights instead of melting smoothly: full height for the deep gorge, two thirds for the middle rings, one third near the rim, gone at the surface.',
          enabled: true,
          params: { levels: 3, passesAbove: 1 },
          inputs: { source: 'depthLeft' },
          display: { mode: 'hidden' },
        },
        {
          id: 'clearing',
          type: 'basinField',
          label: 'the waking clearing',
          folder: 'the labyrinth',
          comment:
            'A tiny bowl reused as a radial mask: 0 at the spawn, 1 twelve tiles out. Multiplying the walls by it melts the labyrinth away around the exact spot you wake — the maze lattice always runs a wall through the origin, so without this you would wake inside rock.',
          enabled: true,
          params: { centerX: 0, centerY: 0, radius: 12, floor: 0 },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'zonedWalls',
          type: 'combineFields',
          label: 'walls at zone height',
          folder: 'the labyrinth',
          comment:
            'The maze masked by its zone height. Deep down this is the full labyrinth; near the rim the same walls survive only as knee-high ridges you can hop onto and walk along; on the surface nothing of it remains.',
          enabled: true,
          params: { operation: COMBINE_MULTIPLY, clamp: 1 },
          inputs: { a: 'walls', b: 'wallZones' },
          display: { mode: 'hidden' },
        },
        {
          id: 'standingWalls',
          type: 'combineFields',
          label: 'walls still standing',
          folder: 'the labyrinth',
          comment:
            'The zoned walls with the waking clearing melted out of them, so the first walls you meet rise from stubs at the clearing’s edge to full towering rock a dozen tiles in. Both wall paints read this field too.',
          enabled: true,
          params: { operation: COMBINE_MULTIPLY, clamp: 1 },
          inputs: { a: 'zonedWalls', b: 'clearing' },
          display: { mode: 'hidden' },
        },
        {
          id: 'wallHeight',
          type: 'constantField',
          label: 'full wall height',
          folder: 'the labyrinth',
          comment:
            'The tallest wall in field units: 0.3 of the 12-level height scale is 3.6 levels of sheer rock — more than three jumps stacked, before the granite crown adds two more tiles on top.',
          enabled: true,
          params: { value: WALL_HEIGHT },
          inputs: {},
          display: { mode: 'hidden' },
        },
        {
          id: 'wallBump',
          type: 'combineFields',
          label: 'wall relief',
          folder: 'the labyrinth',
          comment: 'The standing walls scaled to their real height, ready to raise out of the ground.',
          enabled: true,
          params: { operation: COMBINE_MULTIPLY, clamp: 1 },
          inputs: { a: 'standingWalls', b: 'wallHeight' },
          display: { mode: 'hidden' },
        },
        {
          id: 'built',
          type: 'combineFields',
          label: 'gorge and labyrinth',
          folder: 'the labyrinth',
          comment:
            'The shelves with the walls raised on them. Unclamped, so a wall standing high on the slope keeps its full height instead of being flattened against the ceiling of the 0..1 range.',
          enabled: true,
          params: { operation: COMBINE_ADD, clamp: 0 },
          inputs: { a: 'shelves', b: 'wallBump' },
          display: { mode: 'hidden' },
        },
        {
          id: 'ground',
          type: 'combineFields',
          label: 'the ground',
          folder: 'the labyrinth',
          comment:
            'Everything the boots touch: shelves, plus walls, minus crevasses. The height scale of 12 is the number the whole design is tuned against — it makes each shelf riser and each crevasse exactly one jump.',
          enabled: true,
          params: { operation: COMBINE_SUBTRACT, clamp: 0 },
          inputs: { a: 'built', b: 'cut' },
          display: { mode: 'elevation', heightScale: GORGE_HEIGHT_SCALE },
        },
        {
          id: 'bedrock',
          type: 'thresholdTiles',
          label: 'gorge bedrock',
          folder: 'what you see',
          comment: 'The base coat: bare grey scree over everything. Every later band only overrides part of this.',
          enabled: true,
          params: { threshold: 0, belowTile: -1, aboveTile: defaultTileId('scree') },
          inputs: { source: 'shelves' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'dirt',
          type: 'thresholdTiles',
          label: 'dirt shelves',
          folder: 'what you see',
          comment:
            'Packed dirt from the fourth shelf up. The bands read the shelf field, not the final ground, so wall and crevasse cells keep their own paint.',
          enabled: true,
          params: { threshold: 0.27, belowTile: -1, aboveTile: defaultTileId('packed dirt') },
          inputs: { source: 'shelves' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'turf',
          type: 'thresholdTiles',
          label: 'first turf',
          folder: 'what you see',
          comment: 'Dry pasture from the seventh shelf: the first green, the sign the surface is winning.',
          enabled: true,
          params: { threshold: 0.52, belowTile: -1, aboveTile: defaultTileId('pasture grass') },
          inputs: { source: 'shelves' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'meadow',
          type: 'thresholdTiles',
          label: 'high meadow',
          folder: 'what you see',
          comment: 'Full meadow grass from the tenth shelf, two jumps short of out.',
          enabled: true,
          params: { threshold: 0.77, belowTile: -1, aboveTile: defaultTileId('meadow grass') },
          inputs: { source: 'shelves' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'flowers',
          type: 'thresholdTiles',
          label: 'the surface',
          folder: 'what you see',
          comment: 'Flowers only on the topmost shelf — the rim and the open country beyond it. Standing on these means you made it.',
          enabled: true,
          params: { threshold: 0.98, belowTile: -1, aboveTile: defaultTileId('meadow flowers') },
          inputs: { source: 'shelves' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'crackFloor',
          type: 'thresholdTiles',
          label: 'crevasse floors',
          folder: 'what you see',
          comment:
            'Dark loam along the crevasse lines so a crack reads as a crack from above before your boots find out the hard way.',
          enabled: true,
          params: { threshold: 0.5, belowTile: -1, aboveTile: defaultTileId('forest loam') },
          inputs: { source: 'cracks' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'wallCap',
          type: 'thresholdTiles',
          label: 'paved wall tops',
          folder: 'what you see',
          comment:
            'Flagstone on every standing wall cell — whoever built this labyrinth paved the tops. Walkable on purpose: where the walls have sunk to hoppable ridges near the rim, their tops become paths.',
          enabled: true,
          params: { threshold: 0.2, belowTile: -1, aboveTile: defaultTileId('flagstone plaza') },
          inputs: { source: 'standingWalls' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'wallCrown',
          type: 'thresholdTiles',
          label: 'granite crowns',
          folder: 'what you see',
          comment:
            'Bare granite standing two further tiles proud on the full-height walls of the deep gorge, so from the floor where you wake the labyrinth reads as towering rock rather than garden masonry.',
          enabled: true,
          params: { threshold: 0.9, belowTile: -1, aboveTile: defaultTileId('granite outcrop') },
          inputs: { source: 'standingWalls' },
          display: { mode: 'tileLayer' },
        },
        {
          id: 'rimOaks',
          type: 'scatterPoints',
          label: 'rim oaks',
          folder: 'what you see',
          comment:
            'Oaks only where the bowl has topped out — a treeline ringing the rim that is visible from shelves below, so the way out has a landmark long before it has a route.',
          enabled: true,
          params: { density: 0.02, maskAtLeast: 0.985, maskAtMost: 1 },
          inputs: { mask: 'basin' },
          display: { mode: 'markers', tileId: defaultTileId('oak tree'), glyph: '♠', color: '#3f7a44' },
        },
        {
          id: 'wake',
          type: 'landmarkPoint',
          label: 'where you wake',
          folder: 'what you see',
          comment: 'The bottom of the gorge, the center of the bowl, the one point every slope leads away from.',
          enabled: true,
          params: { x: 0, y: 0 },
          inputs: {},
          display: { mode: 'markers', tileId: -1, glyph: '✦', color: '#ffd27f' },
        },
      ],
    },
  };
}
