export const PERSISTED_UI_KEYS = {
  panelWidths: 'panel.widths',
  collapsedPanels: 'panel.collapsed',
  librarySelection: 'library.selection',
  runningWorld: 'library.runningWorld',
  openLibraryFolders: 'library.openFolders',
  openTileArt: 'assets.openTileArt',
  openCreaturePanels: 'assets.openCreaturePanels',
  openItemPanels: 'assets.openItemPanels',
  openInventoryBackdrops: 'assets.openInventoryBackdrops',
  openCulturePanels: 'assets.openCulturePanels',
  hintsVisible: 'ui.hintsVisible',
  collapsedNodeCards: 'procgen.collapsedNodeCards',
  collapsedNodeFolders: 'procgen.collapsedNodeFolders',
  performancePanelOpen: 'world.performancePanelOpen',
} as const;
