import { describe, test } from 'node:test';
import assert from 'node:assert';
import '@/features/asset-library/worlds/nodes';
import { checkNodeRegistryAndParamSpecs } from '@/features/asset-library/worlds/__tests__/nodeRegistryAndParamSpecs.test';
import { checkProgramCatalog } from '@/features/asset-library/worlds/__tests__/programCatalog.test';
import { checkHashSpreadsItsDraws } from '@/features/asset-library/worlds/__tests__/hashSpreadsItsDraws.test';
import { checkChunkDeterminismAndSignatures } from '@/features/asset-library/worlds/__tests__/chunkDeterminismAndSignatures.test';
import { checkLabyrinthConnectivity } from '@/features/asset-library/worlds/__tests__/labyrinthConnectivity.test';
import { checkLabyrinthChunkTopology } from '@/features/asset-library/worlds/__tests__/labyrinthChunkTopology.test';
import { checkCustomScriptNodes } from '@/features/asset-library/worlds/__tests__/customScriptNodes.test';
import { checkPipelineSanitizeAndEditing } from '@/features/asset-library/worlds/__tests__/pipelineSanitizeAndEditing.test';
import { checkAsciiSnapshotAndPlayerFooting } from '@/features/game/__tests__/asciiSnapshotAndPlayerFooting.test';
import { checkFaceArtEditingOps } from '@/features/asset-library/__tests__/faceArtEditingOps.test';
import { checkTileSurfaceRendering } from '@/features/asset-library/__tests__/tileSurfaceRendering.test';
import { checkGroundHidesWhatIsUnderIt } from '@/features/game/__tests__/groundHidesWhatIsUnderIt.test';
import { checkInkTransparency } from '@/features/game/__tests__/inkTransparency.test';
import { checkCameraMovementAndZoom } from '@/features/game/__tests__/cameraMovementAndZoom.test';
import { checkCharactersOnStage } from '@/features/game/__tests__/charactersOnStage.test';
import { checkViewRecentering } from '@/features/game/__tests__/viewRecentering.test';
import { checkRandomizeAndPermutation } from '@/features/asset-library/worlds/__tests__/randomizeAndPermutation.test';
import { checkTerrainFieldNodes } from '@/features/asset-library/worlds/__tests__/terrainFieldNodes.test';
import { checkHydrologyNodes } from '@/features/asset-library/worlds/__tests__/hydrologyNodes.test';
import { checkVolcanicWorldInvariants } from '@/features/asset-library/worlds/__tests__/volcanicWorldInvariants.test';
import { checkSettlementSpread } from '@/features/asset-library/worlds/__tests__/settlementSpread.test';
import { checkTimeScrubber } from '@/features/asset-library/worlds/__tests__/timeScrubber.test';
import { checkTimeReadersDeclareThemselves } from '@/features/asset-library/worlds/__tests__/timeReadersDeclareThemselves.test';
import { checkStandingAndBrokenWater } from '@/features/game/__tests__/standingAndBrokenWater.test';
import { checkBiomeBands } from '@/features/asset-library/worlds/__tests__/biomeBands.test';
import { checkNodeFolders } from '@/features/asset-library/worlds/__tests__/nodeFolders.test';
import { checkTemplates } from '@/features/asset-library/worlds/__tests__/templates.test';
import { checkWorldSeedsAreDocuments } from '@/features/asset-library/worlds/__tests__/worldSeedsAreDocuments.test';
import { checkSavedWorlds } from '@/features/asset-library/worlds/__tests__/savedWorlds.test';
import { checkNamedWorldSeeds } from '@/features/asset-library/worlds/__tests__/namedWorldSeeds.test';
import { checkSunkenLabyrinthInvariants } from '@/features/asset-library/worlds/__tests__/sunkenLabyrinthInvariants.test';
import { checkWorldSeedLab } from '@/features/asset-library/worlds/__tests__/worldSeedLab.test';
import { checkGenerationLabCharts } from '@/features/asset-library/worlds/__tests__/generationLabCharts.test';
import { checkWorldShotQueue } from '@/features/game/__tests__/worldShotQueue.test';
import { checkWorldSeedSync } from '@/features/asset-library/worlds/__tests__/worldSeedSync.test';
import { checkAgentObservation } from '@/features/agents/__tests__/agentObservation.test';
import { checkOccludedObservation } from '@/features/agents/__tests__/occludedObservation.test';
import { checkElevationObservation } from '@/features/agents/__tests__/elevationObservation.test';
import { checkAgentApiDocs } from '@/features/agents/__tests__/agentApiDocs.test';
import { checkCommandDispatch } from '@/features/agents/__tests__/commandDispatch.test';
import { checkOnlyTheCommandLayerCanMutate } from '@/features/agents/__tests__/commandLayerIsTheOnlyMutator.test';
import { checkLandmarkAndCeilingInvariants } from '@/features/game/__tests__/landmarkAndCeilingInvariants.test';
import { checkInsertAhead } from '@/features/game/__tests__/insertAhead.test';
import { checkTileArtMipInvariants } from '@/features/asset-library/__tests__/tileArtMipInvariants.test';
import { checkTileArtStorageInvariants } from '@/features/asset-library/__tests__/tileArtStorageInvariants.test';
import { checkGeneratedAssetInvariants } from '@/features/asset-library/__tests__/generatedAssetInvariants.test';
import { checkPieceInvariants } from '@/features/asset-library/__tests__/pieceInvariants.test';
import { checkVillageInvariants } from '@/features/asset-library/worlds/__tests__/villageInvariants.test';
import { checkCultureEditing } from '@/features/asset-library/__tests__/cultureEditing.test';
import { checkShapedTileInvariants } from '@/features/asset-library/__tests__/shapedTileInvariants.test';
import { checkMarkerBillboardInvariants } from '@/features/game/__tests__/markerBillboardInvariants.test';
import { checkSourceArchitecture } from './sourceArchitecture.test';
import { sourceCatalogTests } from './sourceCatalog.test';
import { sourceExplorerStateTests } from './sourceExplorerState.test';
import { checkLibraryRowActions } from '@/features/asset-library/__tests__/libraryRowActions.test';
import { checkLibraryRename } from '@/features/asset-library/__tests__/libraryRename.test';
import { checkLibraryViewMode } from '@/features/asset-library/__tests__/libraryViewMode.test';
import { checkAssetFolders } from '@/features/asset-library/__tests__/assetFolders.test';
import { checkDesignBetsStillHold } from './designBetsStillHold.test';
import { checkEveryApiSurfaceIsDescribed } from '@/features/agents/__tests__/everyApiSurfaceIsDescribed.test';
import { checkClaudeMdPointsAtThingsThatExist } from './claudeMdPointsAtThingsThatExist.test';
import { checkDocumentationHasNotRegrown } from './documentationHasNotRegrown.test';
import { checkPerformanceReadouts } from '@/features/game/__tests__/performanceReadouts.test';
import { checkTileHoverReadout } from '@/features/game/__tests__/tileHoverReadout.test';
import { checkAsciiAgentView } from '@/features/game/__tests__/asciiAgentView.test';
import { checkApiArchitecture } from './apiArchitecture.test';
import { checkPanelHintsRespectTheToggle } from './panelHintsRespectTheToggle.test';
import { checkWalkingSimFun } from '@/features/asset-library/worlds/__tests__/walkingSimFun.test';
import { checkSelfPlayLoop } from '@/features/asset-library/worlds/__tests__/selfPlayLoop.test';
import { checkFeatureExtraction } from '@/features/asset-library/worlds/__tests__/featureExtraction.test';
import { checkFeatureViewLayout } from '@/features/asset-library/worlds/__tests__/featureViewLayout.test';
import { routeHandlerTests } from './routeHandlers.test';
import { bootstrapPersistenceTests } from './bootstrapPersistence.test';
import { websocketUpgradeRoutingTests } from '@/features/game/__tests__/websocketUpgradeRouting.test';
import { checkPuzzleSync } from '@/features/game/multiplayer/__tests__/puzzleSync.test';

function check(name: string, condition: boolean): void {
  test(name, () => assert.ok(condition));
}

describe('the node registry', () => checkNodeRegistryAndParamSpecs(check));
describe('the building program catalog', () => checkProgramCatalog(check));
describe('the hashes every world draws from', () => checkHashSpreadsItsDraws(check));
describe('chunk determinism and node signatures', () => checkChunkDeterminismAndSignatures(check));
describe('labyrinths', () => checkLabyrinthConnectivity(check));
describe('the labyrinth chunk topology', () => checkLabyrinthChunkTopology(check));
describe('custom script nodes', () => checkCustomScriptNodes(check));
describe('pipeline sanitize and editing', () => checkPipelineSanitizeAndEditing(check));
describe('the ascii snapshot', () => checkAsciiSnapshotAndPlayerFooting(check));
describe('face art editing', () => checkFaceArtEditingOps(check));
describe('tile surfaces', () => checkTileSurfaceRendering(check));
describe('the depth of ground', () => checkGroundHidesWhatIsUnderIt(check));
describe('transparent ink', () => checkInkTransparency(check));
describe('camera movement and zoom', () => checkCameraMovementAndZoom(check));
describe('characters on stage', () => checkCharactersOnStage(check));
describe('view recentering', () => checkViewRecentering(check));
describe('randomize and permutation', () => checkRandomizeAndPermutation(check));
describe('terrain field nodes', () => checkTerrainFieldNodes(check));
describe('hydrology nodes', () => checkHydrologyNodes(check));
describe('the volcanic world', () => checkVolcanicWorldInvariants(check));
describe('settlement spread', () => checkSettlementSpread(check));
describe('the time scrubber', () => checkTimeScrubber(check));
describe('nodes that read world time', () => checkTimeReadersDeclareThemselves(check));
describe('biome bands', () => checkBiomeBands(check));
describe('node folders', () => checkNodeFolders(check));
describe('standing and broken water', () => checkStandingAndBrokenWater(check));
describe('templates', () => checkTemplates(check));
describe('the named world seeds', () => checkNamedWorldSeeds(check));
describe('the sunken labyrinth', () => checkSunkenLabyrinthInvariants(check));
describe('the world lab', () => checkWorldSeedLab(check));
describe('the generation lab charts', () => checkGenerationLabCharts(check));
describe('the world shot queue', () => checkWorldShotQueue(check));
describe('world seeds shipped in data files sync into the database', () => checkWorldSeedSync(check));
describe('worlds and node groups as documents', () => checkWorldSeedsAreDocuments(check));
describe('saved worlds', () => checkSavedWorlds(check));
describe('agent observation', () => checkAgentObservation(check));
describe('what a character cannot see past', () => checkOccludedObservation(check));
describe('what an agent reads of the ground height', () => checkElevationObservation(check));
describe('the agent api docs', () => checkAgentApiDocs(check));
describe('command dispatch', () => checkCommandDispatch(check));
describe('the mutation boundary', () => checkOnlyTheCommandLayerCanMutate(check));
describe('tile art mips', () => checkTileArtMipInvariants(check));
describe('tile art storage', () => checkTileArtStorageInvariants(check));
describe('shaped tiles and per-voxel facing', () => checkShapedTileInvariants(check));
describe('scattered prop billboards', () => checkMarkerBillboardInvariants(check));
describe('pieces', () => checkPieceInvariants(check));
describe('villages', () => checkVillageInvariants(check));
describe('the cultures editor', () => checkCultureEditing(check));
describe('generated asset kits', () => checkGeneratedAssetInvariants(check));
describe('the source architecture', () => checkSourceArchitecture(check));
describe('the source explorer catalog', sourceCatalogTests);
describe('the source explorer tree', sourceExplorerStateTests);
describe('library row actions', () => checkLibraryRowActions(check));
describe('library view mode', () => checkLibraryViewMode(check));
describe('asset folders', () => checkAssetFolders(check));
describe('renaming a library row', () => checkLibraryRename(check));
describe('documentation', () => {
  checkDocumentationHasNotRegrown(check);
  checkClaudeMdPointsAtThingsThatExist(check);
});
describe('the design bets', () => checkDesignBetsStillHold(check));
describe('the api surface', () => checkEveryApiSurfaceIsDescribed(check));
describe('landmarks and ceilings', () => checkLandmarkAndCeilingInvariants(check));
describe('inserting assets ahead of the player', () => checkInsertAhead(check));
describe('performance readouts', () => checkPerformanceReadouts(check));
describe('the hovered tile readout', () => checkTileHoverReadout(check));
describe('the agent text view', () => checkAsciiAgentView(check));
describe('the API architecture', () => checkApiArchitecture(check));
describe('panel hints', () => checkPanelHintsRespectTheToggle(check));
describe('the walking simulator benchmark', () => checkWalkingSimFun(check));
describe('the self play loop', () => checkSelfPlayLoop(check));
describe('feature extraction', () => checkFeatureExtraction(check));
describe('the features map layout', () => checkFeatureViewLayout(check));
describe('Route Handlers', routeHandlerTests);
describe('browser persistence bootstrap', bootstrapPersistenceTests);
describe('websocket upgrade routing', websocketUpgradeRoutingTests);
describe('puzzle state over the game socket', () => checkPuzzleSync(check));
