import { describe, test } from 'node:test';
import assert from 'node:assert';
import '../procgen/nodes';
import '../abilities/index';
import { checkNodeRegistryAndParamSpecs } from './checkNodeRegistryAndParamSpecs';
import { checkProgramCatalog } from './checkProgramCatalog';
import { checkHashSpreadsItsDraws } from './checkHashSpreadsItsDraws';
import { checkChunkDeterminismAndSignatures } from './checkChunkDeterminismAndSignatures';
import { checkLabyrinthConnectivity } from './checkLabyrinthConnectivity';
import { checkLabyrinthChunkTopology } from './checkLabyrinthChunkTopology';
import { checkCustomScriptNodes } from './checkCustomScriptNodes';
import { checkPipelineSanitizeAndEditing } from './checkPipelineSanitizeAndEditing';
import { checkAsciiSnapshotAndPlayerFooting } from './checkAsciiSnapshotAndPlayerFooting';
import { checkFaceArtEditingOps } from './checkFaceArtEditingOps';
import { checkTileSurfaceRendering } from './checkTileSurfaceRendering';
import { checkGroundHidesWhatIsUnderIt } from './checkGroundHidesWhatIsUnderIt';
import { checkInkTransparency } from './checkInkTransparency';
import { checkCameraMovementAndZoom } from './checkCameraMovementAndZoom';
import { checkViewRecentering } from './checkViewRecentering';
import { checkRandomizeAndPermutation } from './checkRandomizeAndPermutation';
import { checkTerrainFieldNodes } from './checkTerrainFieldNodes';
import { checkHydrologyNodes } from './checkHydrologyNodes';
import { checkVolcanicWorldInvariants } from './checkVolcanicWorldInvariants';
import { checkSettlementSpread } from './checkSettlementSpread';
import { checkStandingAndBrokenWater } from './checkStandingAndBrokenWater';
import { checkBiomeBands } from './checkBiomeBands';
import { checkNodeFolders } from './checkNodeFolders';
import { checkTemplates } from './checkTemplates';
import { checkWorldsAreDocuments } from './checkWorldsAreDocuments';
import { checkNamedWorldPresets } from './checkNamedWorldPresets';
import { checkAgentObservation } from './checkAgentObservation';
import { checkAgentApiDocs } from './checkAgentApiDocs';
import { checkAbilityDispatch } from './checkAbilityDispatch';
import { checkOnlyTheAbilityLayerCanMutate } from './checkAbilityLayerIsTheOnlyMutator';
import { checkLandmarkAndCeilingInvariants } from './checkLandmarkAndCeilingInvariants';
import { checkTileArtMipInvariants } from './checkTileArtMipInvariants';
import { checkTileArtStorageInvariants } from './checkTileArtStorageInvariants';
import { checkGeneratedAssetInvariants } from './checkGeneratedAssetInvariants';
import { checkPieceInvariants } from './checkPieceInvariants';
import { checkVillageInvariants } from './checkVillageInvariants';
import { checkCultureEditing } from './checkCultureEditing';
import { checkShapedTileInvariants } from './checkShapedTileInvariants';
import { checkMarkerBillboardInvariants } from './checkMarkerBillboardInvariants';
import { checkPresentationFoldersAreTheOnlyDomCode } from './checkPresentationFoldersAreTheOnlyDomCode';
import { checkLibraryRowActions } from './checkLibraryRowActions';
import { checkDesignBetsStillHold } from './checkDesignBetsStillHold';
import { checkEveryApiSurfaceIsDescribed } from './checkEveryApiSurfaceIsDescribed';
import { checkClaudeMdPointsAtThingsThatExist } from './checkClaudeMdPointsAtThingsThatExist';
import { checkDocumentationHasNotRegrown } from './checkDocumentationHasNotRegrown';
import { checkPerformanceReadouts } from './checkPerformanceReadouts';
import { checkTileHoverReadout } from './checkTileHoverReadout';
import { checkDevProxyDoesNotShadowSourceFolders } from './checkDevProxyDoesNotShadowSourceFolders';
import { checkPanelHintsRespectTheToggle } from './checkPanelHintsRespectTheToggle';
import { checkFeatureExtraction } from './checkFeatureExtraction';
import { checkFeatureViewLayout } from './checkFeatureViewLayout';

function check(name: string, condition: boolean): void {
  test(name, () => assert.ok(condition));
}

describe('the node registry', () => checkNodeRegistryAndParamSpecs(check));
describe('the building program catalog', () => checkProgramCatalog(check));
describe('the hashes every world draws from', () => checkHashSpreadsItsDraws(check));
describe('chunk determinism and node signatures', () => checkChunkDeterminismAndSignatures(check));
describe('labyrinths', () => checkLabyrinthConnectivity(check));
describe('the labyrinth chunk topology', () => checkLabyrinthChunkTopology(check));
describe('custom script nodes', () => checkCustomScriptNodes(check));
describe('pipeline sanitize and editing', () => checkPipelineSanitizeAndEditing(check));
describe('the ascii snapshot', () => checkAsciiSnapshotAndPlayerFooting(check));
describe('face art editing', () => checkFaceArtEditingOps(check));
describe('tile surfaces', () => checkTileSurfaceRendering(check));
describe('the depth of ground', () => checkGroundHidesWhatIsUnderIt(check));
describe('transparent ink', () => checkInkTransparency(check));
describe('camera movement and zoom', () => checkCameraMovementAndZoom(check));
describe('view recentering', () => checkViewRecentering(check));
describe('randomize and permutation', () => checkRandomizeAndPermutation(check));
describe('terrain field nodes', () => checkTerrainFieldNodes(check));
describe('hydrology nodes', () => checkHydrologyNodes(check));
describe('the volcanic world', () => checkVolcanicWorldInvariants(check));
describe('settlement spread', () => checkSettlementSpread(check));
describe('biome bands', () => checkBiomeBands(check));
describe('node folders', () => checkNodeFolders(check));
describe('standing and broken water', () => checkStandingAndBrokenWater(check));
describe('templates', () => checkTemplates(check));
describe('the named world presets', () => checkNamedWorldPresets(check));
describe('worlds and node groups as documents', () => checkWorldsAreDocuments(check));
describe('agent observation', () => checkAgentObservation(check));
describe('the agent api docs', () => checkAgentApiDocs(check));
describe('ability dispatch', () => checkAbilityDispatch(check));
describe('the mutation boundary', () => checkOnlyTheAbilityLayerCanMutate(check));
describe('tile art mips', () => checkTileArtMipInvariants(check));
describe('tile art storage', () => checkTileArtStorageInvariants(check));
describe('shaped tiles and per-voxel facing', () => checkShapedTileInvariants(check));
describe('scattered prop billboards', () => checkMarkerBillboardInvariants(check));
describe('pieces', () => checkPieceInvariants(check));
describe('villages', () => checkVillageInvariants(check));
describe('the cultures editor', () => checkCultureEditing(check));
describe('generated asset kits', () => checkGeneratedAssetInvariants(check));
describe('the dom boundary', () => checkPresentationFoldersAreTheOnlyDomCode(check));
describe('library row actions', () => checkLibraryRowActions(check));
describe('documentation', () => {
  checkDocumentationHasNotRegrown(check);
  checkClaudeMdPointsAtThingsThatExist(check);
});
describe('the design bets', () => checkDesignBetsStillHold(check));
describe('the api surface', () => checkEveryApiSurfaceIsDescribed(check));
describe('landmarks and ceilings', () => checkLandmarkAndCeilingInvariants(check));
describe('performance readouts', () => checkPerformanceReadouts(check));
describe('the hovered tile readout', () => checkTileHoverReadout(check));
describe('the dev proxy', () => checkDevProxyDoesNotShadowSourceFolders(check));
describe('panel hints', () => checkPanelHintsRespectTheToggle(check));
describe('feature extraction', () => checkFeatureExtraction(check));
describe('the features map layout', () => checkFeatureViewLayout(check));
